<?php namespace PCI\Database;

use DB;

class ParishSeeder extends AbstractSeeder
{

    /**
     * @param array
     */
    private $sql = [
        "INSERT INTO parishes
        (town_id, `desc`, created_at, updated_at, created_by, updated_by)
        VALUES
        (1, 'Altagracia', current_timestamp, current_timestamp, 1, 1),
        (1, 'Antímano', current_timestamp, current_timestamp, 1, 1),
        (1, 'Caricuao', current_timestamp, current_timestamp, 1, 1),
        (1, 'Catedral', current_timestamp, current_timestamp, 1, 1),
        (1, 'Coche', current_timestamp, current_timestamp, 1, 1),
        (1, 'El Junquito', current_timestamp, current_timestamp, 1, 1),
        (1, 'El paraíso', current_timestamp, current_timestamp, 1, 1),
        (1, 'El Recreo', current_timestamp, current_timestamp, 1, 1),
        (1, 'El Valle', current_timestamp, current_timestamp, 1, 1),
        (1, 'La Candelaria', current_timestamp, current_timestamp, 1, 1),
        (1, 'La Pastora', current_timestamp, current_timestamp, 1, 1),
        (1, 'La Vega', current_timestamp, current_timestamp, 1, 1),
        (1, 'Macarao', current_timestamp, current_timestamp, 1, 1),
        (1, 'San Agustín', current_timestamp, current_timestamp, 1, 1),
        (1, 'San Bernardino', current_timestamp, current_timestamp, 1, 1),
        (1, 'San José', current_timestamp, current_timestamp, 1, 1),
        (1, 'San Juan', current_timestamp, current_timestamp, 1, 1),
        (1, 'Santa Rosalia', current_timestamp, current_timestamp, 1, 1),
        (1, 'Santa Teresa', current_timestamp, current_timestamp, 1, 1),
        (1, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (1, '23 de enero', current_timestamp, current_timestamp, 1, 1),
        (1, 'San Pedro', current_timestamp, current_timestamp, 1, 1),
        (2, 'El Cafetal', current_timestamp, current_timestamp, 1, 1),
        (2, 'Las minas de Baruta', current_timestamp, current_timestamp, 1, 1),
        (2, 'Nuestra Señora del Rosario', current_timestamp, current_timestamp, 1, 1),
        (3, 'Chacao', current_timestamp, current_timestamp, 1, 1),
        (4, 'Petare', current_timestamp, current_timestamp, 1, 1),
        (4, 'Leoncio Martinez', current_timestamp, current_timestamp, 1, 1),
        (4, 'La Dolorita', current_timestamp, current_timestamp, 1, 1),
        (4, 'Caucaguita', current_timestamp, current_timestamp, 1, 1),
        (4, 'Filas de Mariche', current_timestamp, current_timestamp, 1, 1),
        (6, 'Araguita', current_timestamp, current_timestamp, 1, 1),
        (6, 'Arevalo Gonzalez', current_timestamp, current_timestamp, 1, 1),
        (6, 'Capaya', current_timestamp, current_timestamp, 1, 1),
        (6, 'Caucagua', current_timestamp, current_timestamp, 1, 1),
        (6, 'El Cafe', current_timestamp, current_timestamp, 1, 1),
        (6, 'Marizapa', current_timestamp, current_timestamp, 1, 1),
        (6, 'Panaquire', current_timestamp, current_timestamp, 1, 1),
        (6, 'Ribas', current_timestamp, current_timestamp, 1, 1),
        (7, 'Cumbo', current_timestamp, current_timestamp, 1, 1),
        (7, 'San Jose Barlovento', current_timestamp, current_timestamp, 1, 1),
        (8, 'Curiepe', current_timestamp, current_timestamp, 1, 1),
        (8, 'Higuerote', current_timestamp, current_timestamp, 1, 1),
        (8, 'Tacarigua', current_timestamp, current_timestamp, 1, 1),
        (9, 'Mamporal', current_timestamp, current_timestamp, 1, 1),
        (10, 'Carrizal', current_timestamp, current_timestamp, 1, 1),
        (11, 'Charallave', current_timestamp, current_timestamp, 1, 1),
        (11, 'Las Brisas', current_timestamp, current_timestamp, 1, 1),
        (12, 'Altagracia de la M', current_timestamp, current_timestamp, 1, 1),
        (12, 'Cecilio Acosta', current_timestamp, current_timestamp, 1, 1),
        (12, 'El Jarillo', current_timestamp, current_timestamp, 1, 1),
        (12, 'Los Teques', current_timestamp, current_timestamp, 1, 1),
        (12, 'Paracotos', current_timestamp, current_timestamp, 1, 1),
        (12, 'San Pedro', current_timestamp, current_timestamp, 1, 1),
        (12, 'Tacata', current_timestamp, current_timestamp, 1, 1),
        (13, 'El Cartanal', current_timestamp, current_timestamp, 1, 1),
        (13, 'Sta Teresa del Tuy', current_timestamp, current_timestamp, 1, 1),
        (14, 'La Democracia', current_timestamp, current_timestamp, 1, 1),
        (14, 'Ocumare del Tuy', current_timestamp, current_timestamp, 1, 1),
        (14, 'Santa Barbara', current_timestamp, current_timestamp, 1, 1),
        (15, 'San Antonio de los altos', current_timestamp, current_timestamp, 1, 1),
        (16, 'El Guapo', current_timestamp, current_timestamp, 1, 1),
        (16, 'Paparo', current_timestamp, current_timestamp, 1, 1),
        (16, 'Tacarigua de la laguna', current_timestamp, current_timestamp, 1, 1),
        (16, 'Rio Chico', current_timestamp, current_timestamp, 1, 1),
        (16, 'San Fernardo del Guapo', current_timestamp, current_timestamp, 1, 1),
        (17, 'Santa Lucia', current_timestamp, current_timestamp, 1, 1),
        (18, 'Cupira', current_timestamp, current_timestamp, 1, 1),
        (18, 'Machurucuto', current_timestamp, current_timestamp, 1, 1),
        (19, 'Guarenas', current_timestamp, current_timestamp, 1, 1),
        (20, 'San Francisco de Yare', current_timestamp, current_timestamp, 1, 1),
        (20, 'San Antonio de Yare', current_timestamp, current_timestamp, 1, 1),
        (21, 'Cua', current_timestamp, current_timestamp, 1, 1),
        (21, 'Nueva Cua', current_timestamp, current_timestamp, 1, 1),
        (22, 'Bolivar', current_timestamp, current_timestamp, 1, 1),
        (22, 'Guatire', current_timestamp, current_timestamp, 1, 1),
        (23, 'Caraballeda', current_timestamp, current_timestamp, 1, 1),
        (23, 'Carayaca', current_timestamp, current_timestamp, 1, 1),
        (23, 'Carlos Soublette', current_timestamp, current_timestamp, 1, 1),
        (23, 'Caruao', current_timestamp, current_timestamp, 1, 1),
        (23, 'Catia la mar', current_timestamp, current_timestamp, 1, 1),
        (23, 'El Junko', current_timestamp, current_timestamp, 1, 1),
        (23, 'La Guaira', current_timestamp, current_timestamp, 1, 1),
        (23, 'Macuto', current_timestamp, current_timestamp, 1, 1),
        (23, 'Maiquetia', current_timestamp, current_timestamp, 1, 1),
        (23, 'Naiguata', current_timestamp, current_timestamp, 1, 1),
        (23, 'Urimare', current_timestamp, current_timestamp, 1, 1),
        (24, 'Camaguan', current_timestamp, current_timestamp, 1, 1),
        (24, 'Puerto Miranda', current_timestamp, current_timestamp, 1, 1),
        (24, 'Uverito', current_timestamp, current_timestamp, 1, 1),
        (25, 'Chaguaramas', current_timestamp, current_timestamp, 1, 1),
        (26, 'El Socorro', current_timestamp, current_timestamp, 1, 1),
        (27, 'Calabozo', current_timestamp, current_timestamp, 1, 1),
        (27, 'El Calvario', current_timestamp, current_timestamp, 1, 1),
        (27, 'El rastro', current_timestamp, current_timestamp, 1, 1),
        (27, 'Guardatinajas', current_timestamp, current_timestamp, 1, 1),
        (28, 'San Rafael de Laya', current_timestamp, current_timestamp, 1, 1),
        (28, 'Tucupido', current_timestamp, current_timestamp, 1, 1),
        (29, 'Altagracia de Orituco', current_timestamp, current_timestamp, 1, 1),
        (29, 'Lezama', current_timestamp, current_timestamp, 1, 1),
        (29, 'Libertad de Orituco', current_timestamp, current_timestamp, 1, 1),
        (29, 'Paso real de Macaira', current_timestamp, current_timestamp, 1, 1),
        (29, 'San Fco de Macaira', current_timestamp, current_timestamp, 1, 1),
        (29, 'San Rafael de Orituco', current_timestamp, current_timestamp, 1, 1),
        (29, 'Soublette', current_timestamp, current_timestamp, 1, 1),
        (30, 'Cantagallo', current_timestamp, current_timestamp, 1, 1),
        (30, 'Parapara', current_timestamp, current_timestamp, 1, 1),
        (30, 'San Juan de los Morros', current_timestamp, current_timestamp, 1, 1),
        (31, 'El Sombrero', current_timestamp, current_timestamp, 1, 1),
        (31, 'Sosa', current_timestamp, current_timestamp, 1, 1),
        (32, 'Cabruta', current_timestamp, current_timestamp, 1, 1),
        (32, 'Las Mercedes', current_timestamp, current_timestamp, 1, 1),
        (32, 'Santa Rita de Manapire', current_timestamp, current_timestamp, 1, 1),
        (33, 'Espino', current_timestamp, current_timestamp, 1, 1),
        (33, 'Valle de la Pascua', current_timestamp, current_timestamp, 1, 1),
        (34, 'Ortiz', current_timestamp, current_timestamp, 1, 1),
        (34, 'Sn Fco de Tiznados', current_timestamp, current_timestamp, 1, 1),
        (34, 'San Jose de Tiznados', current_timestamp, current_timestamp, 1, 1),
        (34, 'Sn Lorenzo de tiznados', current_timestamp, current_timestamp, 1, 1),
        (35, 'San Jose de Unare', current_timestamp, current_timestamp, 1, 1),
        (35, 'Zaraza', current_timestamp, current_timestamp, 1, 1),
        (36, 'Cazorla', current_timestamp, current_timestamp, 1, 1),
        (36, 'Guayabal', current_timestamp, current_timestamp, 1, 1),
        (37, 'San Jose de Guaribe', current_timestamp, current_timestamp, 1, 1),
        (38, 'Altamira', current_timestamp, current_timestamp, 1, 1),
        (38, 'Santa Maria de Ipire', current_timestamp, current_timestamp, 1, 1),
        (39, 'San Mateo', current_timestamp, current_timestamp, 1, 1),
        (41, 'Carmen de Cura', current_timestamp, current_timestamp, 1, 1),
        (41, 'Camatagua', current_timestamp, current_timestamp, 1, 1),
        (42, 'Santa Rita', current_timestamp, current_timestamp, 1, 1),
        (42, 'Francisco de Miranda', current_timestamp, current_timestamp, 1, 1),
        (42, 'Mons Feliciano', current_timestamp, current_timestamp, 1, 1),
        (43, 'Andres Eloy Blanco', current_timestamp, current_timestamp, 1, 1),
        (43, 'Choroni', current_timestamp, current_timestamp, 1, 1),
        (43, 'Joaquin Crespo', current_timestamp, current_timestamp, 1, 1),
        (43, 'Jose Casanova Godoy', current_timestamp, current_timestamp, 1, 1),
        (43, 'Las Delicias', current_timestamp, current_timestamp, 1, 1),
        (43, 'Los Tacariguas', current_timestamp, current_timestamp, 1, 1),
        (43, 'Madre Ma de San Jose', current_timestamp, current_timestamp, 1, 1),
        (43, 'Pedro Jose Ovalies', current_timestamp, current_timestamp, 1, 1),
        (44, 'Santa Cruz', current_timestamp, current_timestamp, 1, 1),
        (45, 'Castor Nieves Rios', current_timestamp, current_timestamp, 1, 1),
        (45, 'La Victoria', current_timestamp, current_timestamp, 1, 1),
        (45, 'Las Guacamayas', current_timestamp, current_timestamp, 1, 1),
        (45, 'Pao de Zarate', current_timestamp, current_timestamp, 1, 1),
        (45, 'Zuata', current_timestamp, current_timestamp, 1, 1),
        (46, 'El Consejo', current_timestamp, current_timestamp, 1, 1),
        (47, 'Palo Negro', current_timestamp, current_timestamp, 1, 1),
        (47, 'Martin de Porres', current_timestamp, current_timestamp, 1, 1),
        (48, 'Ca de Azucar', current_timestamp, current_timestamp, 1, 1),
        (48, 'El Limon', current_timestamp, current_timestamp, 1, 1),
        (49, 'Ocumare de la costa', current_timestamp, current_timestamp, 1, 1),
        (50, 'San Casimiro', current_timestamp, current_timestamp, 1, 1),
        (50, 'Guiripa', current_timestamp, current_timestamp, 1, 1),
        (50, 'Ollas de Caramacate', current_timestamp, current_timestamp, 1, 1),
        (50, 'Valle Morin', current_timestamp, current_timestamp, 1, 1),
        (51, 'San Sebastian', current_timestamp, current_timestamp, 1, 1),
        (52, 'Alfredo Pacheco', current_timestamp, current_timestamp, 1, 1),
        (52, 'Arevalo Aponte', current_timestamp, current_timestamp, 1, 1),
        (52, 'Chuao', current_timestamp, current_timestamp, 1, 1),
        (52, 'Turumero', current_timestamp, current_timestamp, 1, 1),
        (52, 'Saman de Guere', current_timestamp, current_timestamp, 1, 1),
        (53, 'Las Tejerias', current_timestamp, current_timestamp, 1, 1),
        (53, 'Tiara', current_timestamp, current_timestamp, 1, 1),
        (54, 'Bella Vista', current_timestamp, current_timestamp, 1, 1),
        (54, 'Cagua', current_timestamp, current_timestamp, 1, 1),
        (55, 'Colonia Tovar', current_timestamp, current_timestamp, 1, 1),
        (56, 'Barbacoas', current_timestamp, current_timestamp, 1, 1),
        (56, 'Las Peñitas', current_timestamp, current_timestamp, 1, 1),
        (56, 'San Francisco de Cara', current_timestamp, current_timestamp, 1, 1),
        (56, 'Taguay', current_timestamp, current_timestamp, 1, 1),
        (57, 'Augusto Mijares', current_timestamp, current_timestamp, 1, 1),
        (57, 'Villa de cura', current_timestamp, current_timestamp, 1, 1),
        (57, 'Magdaleno', current_timestamp, current_timestamp, 1, 1),
        (57, 'Sam Francisco de Asis', current_timestamp, current_timestamp, 1, 1),
        (57, 'Valles de Tucutunemo', current_timestamp, current_timestamp, 1, 1),
        (58, 'Bejuma', current_timestamp, current_timestamp, 1, 1),
        (58, 'Canoabo', current_timestamp, current_timestamp, 1, 1),
        (58, 'Simon Bolivar', current_timestamp, current_timestamp, 1, 1),
        (59, 'Belen', current_timestamp, current_timestamp, 1, 1),
        (59, 'Guigue', current_timestamp, current_timestamp, 1, 1),
        (59, 'Tacarigua', current_timestamp, current_timestamp, 1, 1),
        (60, 'Agua Caliente', current_timestamp, current_timestamp, 1, 1),
        (60, 'Mariara', current_timestamp, current_timestamp, 1, 1),
        (61, 'Ciudad Alianza', current_timestamp, current_timestamp, 1, 1),
        (61, 'Guacara', current_timestamp, current_timestamp, 1, 1),
        (61, 'Yagua', current_timestamp, current_timestamp, 1, 1),
        (62, 'Moron', current_timestamp, current_timestamp, 1, 1),
        (62, 'Urama', current_timestamp, current_timestamp, 1, 1),
        (63, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (63, 'Tocuyito', current_timestamp, current_timestamp, 1, 1),
        (64, 'Los Guayos', current_timestamp, current_timestamp, 1, 1),
        (65, 'Miranda', current_timestamp, current_timestamp, 1, 1),
        (66, 'Montalban', current_timestamp, current_timestamp, 1, 1),
        (67, 'Naguanagua', current_timestamp, current_timestamp, 1, 1),
        (68, 'Bartolome Salom', current_timestamp, current_timestamp, 1, 1),
        (68, 'Borburata', current_timestamp, current_timestamp, 1, 1),
        (68, 'Democracia', current_timestamp, current_timestamp, 1, 1),
        (68, 'Fraternidad', current_timestamp, current_timestamp, 1, 1),
        (68, 'Goaigoaza', current_timestamp, current_timestamp, 1, 1),
        (68, 'Juan Jose Flores', current_timestamp, current_timestamp, 1, 1),
        (68, 'Patanemo', current_timestamp, current_timestamp, 1, 1),
        (68, 'Union', current_timestamp, current_timestamp, 1, 1),
        (69, 'San Diego', current_timestamp, current_timestamp, 1, 1),
        (70, 'San Joaquin', current_timestamp, current_timestamp, 1, 1),
        (71, 'Candelaria', current_timestamp, current_timestamp, 1, 1),
        (71, 'Catedral', current_timestamp, current_timestamp, 1, 1),
        (71, 'El Socorro', current_timestamp, current_timestamp, 1, 1),
        (71, 'Miguel Peña', current_timestamp, current_timestamp, 1, 1),
        (71, 'Negro Primero', current_timestamp, current_timestamp, 1, 1),
        (71, 'Rafael Urdaneta', current_timestamp, current_timestamp, 1, 1),
        (71, 'San Bias', current_timestamp, current_timestamp, 1, 1),
        (71, 'San Jose', current_timestamp, current_timestamp, 1, 1),
        (71, 'Santa Rosa', current_timestamp, current_timestamp, 1, 1),
        (5, 'El Hatillo', current_timestamp, current_timestamp, 1, 1),
        (93, 'Alto Orinoco La Esmeralda', current_timestamp, current_timestamp, 1, 1),
        (93, 'Huachamacare Acanaña', current_timestamp, current_timestamp, 1, 1),
        (93, 'Marawaka Toky Shamanaña', current_timestamp, current_timestamp, 1, 1),
        (93, 'Mavaka Mavaka', current_timestamp, current_timestamp, 1, 1),
        (93, 'Sierra Parima Parimabé', current_timestamp, current_timestamp, 1, 1),
        (94, 'Ucata Laja Lisa', current_timestamp, current_timestamp, 1, 1),
        (94, 'Yapacana Macuruco', current_timestamp, current_timestamp, 1, 1),
        (94, 'Caname Guarinuma', current_timestamp, current_timestamp, 1, 1),
        (95, 'Fernando Girón Tovar Puerto Ayacucho', current_timestamp, current_timestamp, 1, 1),
        (95, 'Luis Alberto Gómez Puerto Ayacucho', current_timestamp, current_timestamp, 1, 1),
        (95, 'Pahueña Limón de Parhueña', current_timestamp, current_timestamp, 1, 1),
        (95, 'Platanillal Platanillal', current_timestamp, current_timestamp, 1, 1),
        (96, 'Samariapo Samariapo', current_timestamp, current_timestamp, 1, 1),
        (96, 'Sipapo Pendare', current_timestamp, current_timestamp, 1, 1),
        (96, 'Munduapo Munduapo', current_timestamp, current_timestamp, 1, 1),
        (96, 'Guayapo San Pedro del Orinoco', current_timestamp, current_timestamp, 1, 1),
        (97, 'Alto Ventuari Cacurí', current_timestamp, current_timestamp, 1, 1),
        (97, 'Medio Ventuari Manami', current_timestamp, current_timestamp, 1, 1),
        (97, 'Ventuari Marueta', current_timestamp, current_timestamp, 1, 1),
        (98, 'Victorino', current_timestamp, current_timestamp, 1, 1),
        (98, 'Comunidad', current_timestamp, current_timestamp, 1, 1),
        (99, 'Casiquiare Curimacare', current_timestamp, current_timestamp, 1, 1),
        (99, 'Cucuy', current_timestamp, current_timestamp, 1, 1),
        (99, 'Casiquiare Curimacare', current_timestamp, current_timestamp, 1, 1),
        (99, 'Solano Solano', current_timestamp, current_timestamp, 1, 1),
        (72, 'Anaco', current_timestamp, current_timestamp, 1, 1),
        (72, 'San Joaquín', current_timestamp, current_timestamp, 1, 1),
        (73, 'Cachipo', current_timestamp, current_timestamp, 1, 1),
        (73, 'Aragua de Barcelona', current_timestamp, current_timestamp, 1, 1),
        (78, 'Lechería', current_timestamp, current_timestamp, 1, 1),
        (78, 'El Morro', current_timestamp, current_timestamp, 1, 1),
        (87, 'Puerto Píritu', current_timestamp, current_timestamp, 1, 1),
        (87, 'San Miguel', current_timestamp, current_timestamp, 1, 1),
        (87, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (77, 'Valle de Guanape', current_timestamp, current_timestamp, 1, 1),
        (77, 'Santa Bárbara', current_timestamp, current_timestamp, 1, 1),
        (85, 'Atapirire', current_timestamp, current_timestamp, 1, 1),
        (85, 'Boca del Pao', current_timestamp, current_timestamp, 1, 1),
        (85, 'El Pao', current_timestamp, current_timestamp, 1, 1),
        (85, 'Pariaguán', current_timestamp, current_timestamp, 1, 1),
        (81, 'Guanta', current_timestamp, current_timestamp, 1, 1),
        (81, 'Chorrerón', current_timestamp, current_timestamp, 1, 1),
        (82, 'Mamo', current_timestamp, current_timestamp, 1, 1),
        (82, 'Soledad', current_timestamp, current_timestamp, 1, 1),
        (86, 'Mapire', current_timestamp, current_timestamp, 1, 1),
        (86, 'Piar', current_timestamp, current_timestamp, 1, 1),
        (86, 'Santa Clara', current_timestamp, current_timestamp, 1, 1),
        (86, 'San Diego de Cabrutica', current_timestamp, current_timestamp, 1, 1),
        (86, 'Uverito', current_timestamp, current_timestamp, 1, 1),
        (86, 'Zuata', current_timestamp, current_timestamp, 1, 1),
        (92, 'Puerto La Cruz', current_timestamp, current_timestamp, 1, 1),
        (92, 'Pozuelos', current_timestamp, current_timestamp, 1, 1),
        (76, 'Onoto', current_timestamp, current_timestamp, 1, 1),
        (76, 'San Pablo', current_timestamp, current_timestamp, 1, 1),
        (83, 'San Mateo', current_timestamp, current_timestamp, 1, 1),
        (83, 'El Carito', current_timestamp, current_timestamp, 1, 1),
        (83, 'Santa Inés', current_timestamp, current_timestamp, 1, 1),
        (83, 'La Romereña', current_timestamp, current_timestamp, 1, 1),
        (75, 'Clarines', current_timestamp, current_timestamp, 1, 1),
        (75, 'Guanape', current_timestamp, current_timestamp, 1, 1),
        (75, 'Sabana de Uchire', current_timestamp, current_timestamp, 1, 1),
        (79, 'Cantaura', current_timestamp, current_timestamp, 1, 1),
        (79, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (79, 'Santa Rosa', current_timestamp, current_timestamp, 1, 1),
        (79, 'Urica', current_timestamp, current_timestamp, 1, 1),
        (88, 'Píritu', current_timestamp, current_timestamp, 1, 1),
        (88, 'San Francisco', current_timestamp, current_timestamp, 1, 1),
        (80, 'San José de Guanipa', current_timestamp, current_timestamp, 1, 1),
        (89, 'Boca de Uchire', current_timestamp, current_timestamp, 1, 1),
        (89, 'Boca de Chávez', current_timestamp, current_timestamp, 1, 1),
        (90, 'Pueblo Nuevo', current_timestamp, current_timestamp, 1, 1),
        (90, 'Santa Ana', current_timestamp, current_timestamp, 1, 1),
        (74, 'Bergatín', current_timestamp, current_timestamp, 1, 1),
        (74, 'Caigua', current_timestamp, current_timestamp, 1, 1),
        (74, 'El Carmen', current_timestamp, current_timestamp, 1, 1),
        (74, 'El Pilar', current_timestamp, current_timestamp, 1, 1),
        (74, 'Naricual', current_timestamp, current_timestamp, 1, 1),
        (74, 'San Cristóbal', current_timestamp, current_timestamp, 1, 1),
        (91, 'Edmundo Barrios', current_timestamp, current_timestamp, 1, 1),
        (91, 'Miguel Otero Silva', current_timestamp, current_timestamp, 1, 1),
        (84, 'El Chaparro', current_timestamp, current_timestamp, 1, 1),
        (84, 'Tomás Alfaro', current_timestamp, current_timestamp, 1, 1),
        (84, 'Calatrava', current_timestamp, current_timestamp, 1, 1),
        (100, 'Achaguas', current_timestamp, current_timestamp, 1, 1);",
    "INSERT INTO parishes
        (town_id, `desc`, created_at, updated_at, created_by, updated_by)
        VALUES
        (100, 'Apurito', current_timestamp, current_timestamp, 1, 1),
        (100, 'El Yagual', current_timestamp, current_timestamp, 1, 1),
        (100, 'Guachara', current_timestamp, current_timestamp, 1, 1),
        (100, 'Mucuritas', current_timestamp, current_timestamp, 1, 1),
        (100, 'Queseras del medio', current_timestamp, current_timestamp, 1, 1),
        (101, 'Biruaca', current_timestamp, current_timestamp, 1, 1),
        (102, 'Bruzual', current_timestamp, current_timestamp, 1, 1),
        (102, 'Mantecal', current_timestamp, current_timestamp, 1, 1),
        (102, 'Quintero', current_timestamp, current_timestamp, 1, 1),
        (102, 'Rincón Hondo', current_timestamp, current_timestamp, 1, 1),
        (102, 'San Vicente', current_timestamp, current_timestamp, 1, 1),
        (104, 'San Juan de Payara', current_timestamp, current_timestamp, 1, 1),
        (104, 'Codazzzi', current_timestamp, current_timestamp, 1, 1),
        (104, 'Cunaviche', current_timestamp, current_timestamp, 1, 1),
        (106, 'San Fernando', current_timestamp, current_timestamp, 1, 1),
        (106, 'El Recre0', current_timestamp, current_timestamp, 1, 1),
        (106, 'Peñalver', current_timestamp, current_timestamp, 1, 1),
        (106, 'San Rafael de Atamaica', current_timestamp, current_timestamp, 1, 1),
        (103, 'Guasdualito', current_timestamp, current_timestamp, 1, 1),
        (103, 'Aramendi', current_timestamp, current_timestamp, 1, 1),
        (103, 'El Amparo', current_timestamp, current_timestamp, 1, 1),
        (103, 'San Camilo', current_timestamp, current_timestamp, 1, 1),
        (103, 'Urdaneta', current_timestamp, current_timestamp, 1, 1),
        (105, 'Elorza', current_timestamp, current_timestamp, 1, 1),
        (105, 'La Trinidad', current_timestamp, current_timestamp, 1, 1),
        (107, 'Sabaneta', current_timestamp, current_timestamp, 1, 1),
        (107, 'Juan Antonio Rodríguez Domínguez', current_timestamp, current_timestamp, 1, 1),
        (108, 'El Cantón', current_timestamp, current_timestamp, 1, 1),
        (108, 'Santa Cruz de Guacas', current_timestamp, current_timestamp, 1, 1),
        (108, 'Puerto Vivas', current_timestamp, current_timestamp, 1, 1),
        (109, 'Ticoporo', current_timestamp, current_timestamp, 1, 1),
        (109, 'Nicolás Pulido', current_timestamp, current_timestamp, 1, 1),
        (109, 'Andrés Bello', current_timestamp, current_timestamp, 1, 1),
        (110, 'Arismendi', current_timestamp, current_timestamp, 1, 1),
        (110, 'Guadarrama', current_timestamp, current_timestamp, 1, 1),
        (110, 'La Unión', current_timestamp, current_timestamp, 1, 1),
        (110, 'San Antonio', current_timestamp, current_timestamp, 1, 1),
        (111, 'Barinas', current_timestamp, current_timestamp, 1, 1),
        (111, 'Alberto Arvelo Larriva', current_timestamp, current_timestamp, 1, 1),
        (111, 'San Silvestre', current_timestamp, current_timestamp, 1, 1),
        (111, 'Santa Inés', current_timestamp, current_timestamp, 1, 1),
        (111, 'Santa Lucía', current_timestamp, current_timestamp, 1, 1),
        (111, 'Torunos', current_timestamp, current_timestamp, 1, 1),
        (111, 'El Carmen', current_timestamp, current_timestamp, 1, 1),
        (111, 'Rómulo Betancourt', current_timestamp, current_timestamp, 1, 1),
        (111, 'Corazón de Jesús', current_timestamp, current_timestamp, 1, 1),
        (111, 'Ramón Ignacio', current_timestamp, current_timestamp, 1, 1),
        (111, 'Alto Barinas', current_timestamp, current_timestamp, 1, 1),
        (111, 'Manuel Palacio Fajardo', current_timestamp, current_timestamp, 1, 1),
        (111, 'Juan Antonio Rodríguez Domínguez', current_timestamp, current_timestamp, 1, 1),
        (111, 'Dominga Ortiz de Páez', current_timestamp, current_timestamp, 1, 1),
        (112, 'Barinitas', current_timestamp, current_timestamp, 1, 1),
        (112, 'Altamira de Cáceres', current_timestamp, current_timestamp, 1, 1),
        (112, 'Calderas', current_timestamp, current_timestamp, 1, 1),
        (113, 'Barracas', current_timestamp, current_timestamp, 1, 1),
        (113, 'El Socorro', current_timestamp, current_timestamp, 1, 1),
        (113, 'Mazparrito', current_timestamp, current_timestamp, 1, 1),
        (114, 'Santa Bárbara', current_timestamp, current_timestamp, 1, 1),
        (114, 'Pedro Briceño Méndez', current_timestamp, current_timestamp, 1, 1),
        (114, 'Ramón Ignacio Méndez', current_timestamp, current_timestamp, 1, 1),
        (114, 'José Ignacio del Pumar', current_timestamp, current_timestamp, 1, 1),
        (115, 'Obispos', current_timestamp, current_timestamp, 1, 1),
        (115, 'Los Guasimitos', current_timestamp, current_timestamp, 1, 1),
        (115, 'El Real', current_timestamp, current_timestamp, 1, 1),
        (115, 'La Luz', current_timestamp, current_timestamp, 1, 1),
        (116, 'Ciudad Bolívia', current_timestamp, current_timestamp, 1, 1),
        (116, 'José Ignacio Briceño', current_timestamp, current_timestamp, 1, 1),
        (116, 'José Félix Ribas', current_timestamp, current_timestamp, 1, 1),
        (116, 'Páez', current_timestamp, current_timestamp, 1, 1),
        (117, 'Libertad', current_timestamp, current_timestamp, 1, 1),
        (117, 'Dolores', current_timestamp, current_timestamp, 1, 1),
        (117, 'Santa Rosa', current_timestamp, current_timestamp, 1, 1),
        (117, 'Palacio Fajardo', current_timestamp, current_timestamp, 1, 1),
        (117, 'Simón Rodríguez', current_timestamp, current_timestamp, 1, 1),
        (118, 'Ciudad de Nutrias', current_timestamp, current_timestamp, 1, 1),
        (118, 'El Regalo', current_timestamp, current_timestamp, 1, 1),
        (118, 'Puerto Nutrias', current_timestamp, current_timestamp, 1, 1),
        (118, 'Santa Catalina', current_timestamp, current_timestamp, 1, 1),
        (118, 'Simón Bolívar', current_timestamp, current_timestamp, 1, 1),
        (119, 'Cachamay', current_timestamp, current_timestamp, 1, 1),
        (119, 'Chirica', current_timestamp, current_timestamp, 1, 1),
        (119, 'Dalla Costa', current_timestamp, current_timestamp, 1, 1),
        (119, 'Once de Abril', current_timestamp, current_timestamp, 1, 1),
        (119, 'Simón Bolívar', current_timestamp, current_timestamp, 1, 1),
        (119, 'Unare', current_timestamp, current_timestamp, 1, 1),
        (119, 'Universidad', current_timestamp, current_timestamp, 1, 1),
        (119, 'Vista al Sol', current_timestamp, current_timestamp, 1, 1),
        (119, 'Pozo Verde', current_timestamp, current_timestamp, 1, 1),
        (119, 'Yocoima', current_timestamp, current_timestamp, 1, 1),
        (119, '5 de Julio', current_timestamp, current_timestamp, 1, 1),
        (120, 'Cedeño', current_timestamp, current_timestamp, 1, 1),
        (120, 'Altagracia', current_timestamp, current_timestamp, 1, 1),
        (120, 'Ascensión Farreras', current_timestamp, current_timestamp, 1, 1),
        (120, 'Guaniamo', current_timestamp, current_timestamp, 1, 1),
        (120, 'La Urbana', current_timestamp, current_timestamp, 1, 1),
        (120, 'Pijiguaos', current_timestamp, current_timestamp, 1, 1),
        (121, 'El Callao', current_timestamp, current_timestamp, 1, 1),
        (122, 'Gran Sabana', current_timestamp, current_timestamp, 1, 1),
        (122, 'Ikabarú', current_timestamp, current_timestamp, 1, 1),
        (123, 'Catedral', current_timestamp, current_timestamp, 1, 1),
        (123, 'Zea', current_timestamp, current_timestamp, 1, 1),
        (123, 'Orinoco', current_timestamp, current_timestamp, 1, 1),
        (123, 'José Antonio Páez', current_timestamp, current_timestamp, 1, 1),
        (123, 'Marhuanta', current_timestamp, current_timestamp, 1, 1),
        (123, 'Agua Salada', current_timestamp, current_timestamp, 1, 1),
        (123, 'Vista Hermosa', current_timestamp, current_timestamp, 1, 1),
        (123, 'La Sabanita', current_timestamp, current_timestamp, 1, 1),
        (123, 'Panapana', current_timestamp, current_timestamp, 1, 1),
        (129, 'Padre Pedro Chien', current_timestamp, current_timestamp, 1, 1),
        (129, 'Río Grande', current_timestamp, current_timestamp, 1, 1),
        (124, 'Andrés Eloy Blanco', current_timestamp, current_timestamp, 1, 1),
        (124, 'Pedro Cova', current_timestamp, current_timestamp, 1, 1),
        (125, 'Raúl Leoni', current_timestamp, current_timestamp, 1, 1),
        (125, 'Barceloneta', current_timestamp, current_timestamp, 1, 1),
        (125, 'Santa Bárbara', current_timestamp, current_timestamp, 1, 1),
        (125, 'San Francisco', current_timestamp, current_timestamp, 1, 1),
        (126, 'Roscio', current_timestamp, current_timestamp, 1, 1),
        (126, 'Salóm', current_timestamp, current_timestamp, 1, 1),
        (127, 'Sifontes', current_timestamp, current_timestamp, 1, 1),
        (127, 'Dalla Costa', current_timestamp, current_timestamp, 1, 1),
        (127, 'San Isidro ', current_timestamp, current_timestamp, 1, 1),
        (128, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (128, 'Aripao', current_timestamp, current_timestamp, 1, 1),
        (128, 'Guarataro', current_timestamp, current_timestamp, 1, 1),
        (128, 'Las Majadas', current_timestamp, current_timestamp, 1, 1),
        (128, 'Moitaco ', current_timestamp, current_timestamp, 1, 1),
        (130, 'Cojedes', current_timestamp, current_timestamp, 1, 1),
        (130, 'Juan de Mata Suárez', current_timestamp, current_timestamp, 1, 1),
        (134, 'El Pao', current_timestamp, current_timestamp, 1, 1),
        (131, 'Tinaquillo', current_timestamp, current_timestamp, 1, 1),
        (132, 'El Baúl', current_timestamp, current_timestamp, 1, 1),
        (132, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (133, 'La Aguadita', current_timestamp, current_timestamp, 1, 1),
        (133, 'Macapo', current_timestamp, current_timestamp, 1, 1),
        (135, 'El Amparo', current_timestamp, current_timestamp, 1, 1),
        (135, 'Libertad de Cojedes', current_timestamp, current_timestamp, 1, 1),
        (136, 'Rómulo Gallegos', current_timestamp, current_timestamp, 1, 1),
        (137, 'San Carlos de Austria', current_timestamp, current_timestamp, 1, 1),
        (137, 'Juan Ángel Bravo', current_timestamp, current_timestamp, 1, 1),
        (137, 'Manuel Manrique', current_timestamp, current_timestamp, 1, 1),
        (138, 'General en Jefe José Laurencio Silva', current_timestamp, current_timestamp, 1, 1),
        (139, 'Curiapo', current_timestamp, current_timestamp, 1, 1),
        (139, 'Almirante Luis Brión', current_timestamp, current_timestamp, 1, 1),
        (139, 'Francisco Aniceto Lugo Boca de Cuyubini', current_timestamp, current_timestamp, 1, 1),
        (139, 'Manuel Renaud', current_timestamp, current_timestamp, 1, 1),
        (139, 'Padre Barral', current_timestamp, current_timestamp, 1, 1),
        (139, 'Santos de Abelgas', current_timestamp, current_timestamp, 1, 1),
        (140, 'Imataca Moruca', current_timestamp, current_timestamp, 1, 1),
        (140, 'Cinco de Julio Piacoa', current_timestamp, current_timestamp, 1, 1),
        (140, 'Juan Bautista Arismendi', current_timestamp, current_timestamp, 1, 1),
        (140, 'Manuel Piar Santa Catalina', current_timestamp, current_timestamp, 1, 1),
        (140, 'Rómulo Gallegos', current_timestamp, current_timestamp, 1, 1),
        (141, 'Pedernales', current_timestamp, current_timestamp, 1, 1),
        (141, 'Luis Beltrán Prieto Figueroa', current_timestamp, current_timestamp, 1, 1),
        (142, 'San José (Delta Amacuro) Hacienda del Medio', current_timestamp, current_timestamp, 1, 1),
        (142, 'José Vidal Marcano Caparal de Guara', current_timestamp, current_timestamp, 1, 1),
        (142, 'Juan Millán Urbanización Leonardo Ruíz Pineda', current_timestamp, current_timestamp, 1, 1),
        (142, 'Leonardo Ruíz Pineda Paloma', current_timestamp, current_timestamp, 1, 1),
        (142, 'Mariscal Antonio José de Sucre', current_timestamp, current_timestamp, 1, 1),
        (142, 'Monseñor Argimiro García San Rafael', current_timestamp, current_timestamp, 1, 1),
        (142, 'San Rafael', current_timestamp, current_timestamp, 1, 1),
        (142, 'Virgen del Valle', current_timestamp, current_timestamp, 1, 1),
        (143, 'Capadare', current_timestamp, current_timestamp, 1, 1),
        (143, 'La Pastora', current_timestamp, current_timestamp, 1, 1),
        (143, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (143, 'San Juan de los Cayos', current_timestamp, current_timestamp, 1, 1),
        (144, 'Aracua', current_timestamp, current_timestamp, 1, 1),
        (144, 'La Peña', current_timestamp, current_timestamp, 1, 1),
        (144, 'San Luis', current_timestamp, current_timestamp, 1, 1),
        (145, 'Bariro', current_timestamp, current_timestamp, 1, 1),
        (145, 'Borojó', current_timestamp, current_timestamp, 1, 1),
        (145, 'Capatárida', current_timestamp, current_timestamp, 1, 1),
        (145, 'Guajiro', current_timestamp, current_timestamp, 1, 1),
        (145, 'Seque', current_timestamp, current_timestamp, 1, 1),
        (145, 'Zazárida', current_timestamp, current_timestamp, 1, 1),
        (145, 'Valle de Eroa', current_timestamp, current_timestamp, 1, 1),
        (146, 'Cacique Manaure', current_timestamp, current_timestamp, 1, 1),
        (147, 'Norte', current_timestamp, current_timestamp, 1, 1),
        (147, 'Carirubana', current_timestamp, current_timestamp, 1, 1),
        (147, 'Santa Ana', current_timestamp, current_timestamp, 1, 1),
        (147, 'Urbana Punta Cardón', current_timestamp, current_timestamp, 1, 1),
        (148, 'La Vela de Coro', current_timestamp, current_timestamp, 1, 1),
        (148, 'Acurigua', current_timestamp, current_timestamp, 1, 1),
        (148, 'Guaibacoa', current_timestamp, current_timestamp, 1, 1),
        (148, 'Las Calderas', current_timestamp, current_timestamp, 1, 1),
        (148, 'Macoruca', current_timestamp, current_timestamp, 1, 1),
        (149, 'Dabajuro', current_timestamp, current_timestamp, 1, 1),
        (150, 'Agua Clara', current_timestamp, current_timestamp, 1, 1),
        (150, 'Avaria', current_timestamp, current_timestamp, 1, 1),
        (150, 'Pedregal', current_timestamp, current_timestamp, 1, 1),
        (150, 'Piedra Grande', current_timestamp, current_timestamp, 1, 1),
        (150, 'Purureche', current_timestamp, current_timestamp, 1, 1),
        (151, 'Adaure', current_timestamp, current_timestamp, 1, 1),
        (151, 'Adícora', current_timestamp, current_timestamp, 1, 1),
        (151, 'Baraived', current_timestamp, current_timestamp, 1, 1),
        (151, 'Buena Vista', current_timestamp, current_timestamp, 1, 1),
        (151, 'Jadacaquiva', current_timestamp, current_timestamp, 1, 1),
        (151, 'El Vínculo', current_timestamp, current_timestamp, 1, 1),
        (151, 'El Hato', current_timestamp, current_timestamp, 1, 1),
        (151, 'Moruy', current_timestamp, current_timestamp, 1, 1),
        (151, 'Pueblo Nuevo', current_timestamp, current_timestamp, 1, 1);",
        "INSERT INTO parishes
        (town_id, `desc`, created_at, updated_at, created_by, updated_by)
        VALUES
        (152, 'Agua Larga', current_timestamp, current_timestamp, 1, 1),
        (152, 'Churuguara', current_timestamp, current_timestamp, 1, 1),
        (152, 'El Paují', current_timestamp, current_timestamp, 1, 1),
        (152, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (152, 'Mapararí', current_timestamp, current_timestamp, 1, 1),
        (153, 'Jacura', current_timestamp, current_timestamp, 1, 1),
        (154, 'Los Taques', current_timestamp, current_timestamp, 1, 1),
        (155, 'Mene de Mauroa', current_timestamp, current_timestamp, 1, 1),
        (156, 'Guzmán Guillermo', current_timestamp, current_timestamp, 1, 1),
        (156, 'Mitare ', current_timestamp, current_timestamp, 1, 1),
        (156, 'Río Seco', current_timestamp, current_timestamp, 1, 1),
        (156, 'Sabaneta', current_timestamp, current_timestamp, 1, 1),
        (156, 'Santa Ana', current_timestamp, current_timestamp, 1, 1),
        (157, 'Boca del Tocuyo', current_timestamp, current_timestamp, 1, 1),
        (157, 'Chichiriviche', current_timestamp, current_timestamp, 1, 1),
        (158, 'Palmasola', current_timestamp, current_timestamp, 1, 1),
        (159, 'Cabure', current_timestamp, current_timestamp, 1, 1),
        (159, 'Curimagua', current_timestamp, current_timestamp, 1, 1),
        (160, 'San José de la Costa', current_timestamp, current_timestamp, 1, 1),
        (160, 'Píritu', current_timestamp, current_timestamp, 1, 1),
        (161, 'Capital San Francisco', current_timestamp, current_timestamp, 1, 1),
        (162, 'Tucacas', current_timestamp, current_timestamp, 1, 1),
        (162, 'Boca de Aroa', current_timestamp, current_timestamp, 1, 1),
        (163, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (164, 'Tocópero', current_timestamp, current_timestamp, 1, 1),
        (165, 'Santa Cruz de Bucaral', current_timestamp, current_timestamp, 1, 1),
        (166, 'Bruzual', current_timestamp, current_timestamp, 1, 1),
        (166, 'Urumaco', current_timestamp, current_timestamp, 1, 1),
        (167, 'Puerto Cumarebo', current_timestamp, current_timestamp, 1, 1),
        (167, 'La Ciénaga', current_timestamp, current_timestamp, 1, 1),
        (167, 'La Soledad', current_timestamp, current_timestamp, 1, 1),
        (167, 'Pueblo Cumarebo', current_timestamp, current_timestamp, 1, 1),
        (167, 'Zazárida', current_timestamp, current_timestamp, 1, 1),
        (168, 'Pio Tamayo', current_timestamp, current_timestamp, 1, 1),
        (168, 'Quebrada Honda de Guache', current_timestamp, current_timestamp, 1, 1),
        (169, 'Freitez', current_timestamp, current_timestamp, 1, 1),
        (169, 'José María Blanco', current_timestamp, current_timestamp, 1, 1),
        (172, 'Anzoátegui', current_timestamp, current_timestamp, 1, 1),
        (172, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (172, 'Guárico', current_timestamp, current_timestamp, 1, 1),
        (172, 'Hilario Luna y Luna', current_timestamp, current_timestamp, 1, 1),
        (173, 'Cabudare', current_timestamp, current_timestamp, 1, 1),
        (173, 'Agua Viva', current_timestamp, current_timestamp, 1, 1),
        (172, 'Morán', current_timestamp, current_timestamp, 1, 1),
        (174, 'Buría', current_timestamp, current_timestamp, 1, 1),
        (174, 'Sarare', current_timestamp, current_timestamp, 1, 1),
        (175, 'Altagracia', current_timestamp, current_timestamp, 1, 1),
        (175, 'Lara', current_timestamp, current_timestamp, 1, 1),
        (175, 'Chiquinquira', current_timestamp, current_timestamp, 1, 1),
        (176, 'Siquisique', current_timestamp, current_timestamp, 1, 1),
        (176, 'Moroturo', current_timestamp, current_timestamp, 1, 1),
        (170, 'Barquisimeto', current_timestamp, current_timestamp, 1, 1),
        (171, 'Quibor', current_timestamp, current_timestamp, 1, 1),
        (177, 'Betancourt', current_timestamp, current_timestamp, 1, 1),
        (177, 'Páez', current_timestamp, current_timestamp, 1, 1),
        (177, 'Rómulo Gallegos', current_timestamp, current_timestamp, 1, 1),
        (177, 'Gabriel Picón Gonzále', current_timestamp, current_timestamp, 1, 1),
        (177, 'Héctor Amable Mora', current_timestamp, current_timestamp, 1, 1),
        (178, 'La Azulita', current_timestamp, current_timestamp, 1, 1),
        (179, 'Santa Cruz de Mora', current_timestamp, current_timestamp, 1, 1),
        (179, 'Mesa de Las Palmas', current_timestamp, current_timestamp, 1, 1),
        (180, 'Aricagua', current_timestamp, current_timestamp, 1, 1),
        (181, 'Capurí', current_timestamp, current_timestamp, 1, 1),
        (181, 'Chacantá', current_timestamp, current_timestamp, 1, 1),
        (181, 'Guaimaral', current_timestamp, current_timestamp, 1, 1),
        (181, 'Mucuchachí', current_timestamp, current_timestamp, 1, 1),
        (182, 'Fernández Peña (Ejido)', current_timestamp, current_timestamp, 1, 1),
        (182, 'Acequias', current_timestamp, current_timestamp, 1, 1),
        (182, 'Jají', current_timestamp, current_timestamp, 1, 1),
        (182, 'La Mesa', current_timestamp, current_timestamp, 1, 1),
        (182, 'San José del Sur', current_timestamp, current_timestamp, 1, 1),
        (183, 'Tucaní', current_timestamp, current_timestamp, 1, 1),
        (184, 'Santo Domingo', current_timestamp, current_timestamp, 1, 1),
        (185, 'Guaraque', current_timestamp, current_timestamp, 1, 1),
        (186, 'Arapuey', current_timestamp, current_timestamp, 1, 1),
        (186, 'Palmira', current_timestamp, current_timestamp, 1, 1),
        (187, 'Torondoy', current_timestamp, current_timestamp, 1, 1),
        (188, 'Antonio Spinetti Dini', current_timestamp, current_timestamp, 1, 1),
        (188, 'Arias', current_timestamp, current_timestamp, 1, 1),
        (188, 'Caracciolo Parra Pérez', current_timestamp, current_timestamp, 1, 1),
        (188, 'Domingo Peña ', current_timestamp, current_timestamp, 1, 1),
        (188, 'El Llano', current_timestamp, current_timestamp, 1, 1),
        (188, 'Gonzalo Picón Febres', current_timestamp, current_timestamp, 1, 1),
        (188, 'Jacinto Plaza', current_timestamp, current_timestamp, 1, 1),
        (188, 'Juan Rodríguez Suárez', current_timestamp, current_timestamp, 1, 1),
        (188, 'Lasso de la Vega', current_timestamp, current_timestamp, 1, 1),
        (188, 'Mariano Picón Sala', current_timestamp, current_timestamp, 1, 1),
        (188, 'Milla', current_timestamp, current_timestamp, 1, 1),
        (188, 'Osuna Rodríguez', current_timestamp, current_timestamp, 1, 1),
        (188, 'Sagrario', current_timestamp, current_timestamp, 1, 1),
        (188, 'El Morro', current_timestamp, current_timestamp, 1, 1),
        (188, 'Los Nevados', current_timestamp, current_timestamp, 1, 1),
        (189, 'Andrés Eloy Blanco', current_timestamp, current_timestamp, 1, 1),
        (189, 'La Venta', current_timestamp, current_timestamp, 1, 1),
        (189, 'Piñango', current_timestamp, current_timestamp, 1, 1),
        (189, 'Timotes', current_timestamp, current_timestamp, 1, 1),
        (190, 'Eloy Paredes', current_timestamp, current_timestamp, 1, 1),
        (190, 'San Rafael de Alcázar', current_timestamp, current_timestamp, 1, 1),
        (191, 'Santa María de Caparo', current_timestamp, current_timestamp, 1, 1),
        (192, 'Pueblo Llano', current_timestamp, current_timestamp, 1, 1),
        (193, 'Cacute', current_timestamp, current_timestamp, 1, 1),
        (193, 'Mucuchíes', current_timestamp, current_timestamp, 1, 1),
        (194, 'Gerónimo Maldonado', current_timestamp, current_timestamp, 1, 1),
        (194, 'Bailadores', current_timestamp, current_timestamp, 1, 1),
        (195, 'Tabay', current_timestamp, current_timestamp, 1, 1),
        (196, 'Chiguará', current_timestamp, current_timestamp, 1, 1),
        (196, 'Estánquez', current_timestamp, current_timestamp, 1, 1),
        (196, 'Lagunillas', current_timestamp, current_timestamp, 1, 1),
        (196, 'Pueblo Nuevo del Sur', current_timestamp, current_timestamp, 1, 1),
        (196, 'San Juan', current_timestamp, current_timestamp, 1, 1),
        (197, 'El Amparo', current_timestamp, current_timestamp, 1, 1),
        (197, 'El Llano', current_timestamp, current_timestamp, 1, 1),
        (197, 'San Francisco', current_timestamp, current_timestamp, 1, 1),
        (197, 'Tovar', current_timestamp, current_timestamp, 1, 1),
        (198, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (198, 'María de la Concepción Palacios Blanco', current_timestamp, current_timestamp, 1, 1),
        (198, 'Nueva Bolivia', current_timestamp, current_timestamp, 1, 1),
        (198, 'Santa Apolonia', current_timestamp, current_timestamp, 1, 1),
        (199, 'Caño El Tigre', current_timestamp, current_timestamp, 1, 1),
        (199, 'Zea', current_timestamp, current_timestamp, 1, 1),
        (200, 'San Antonio de Maturín', current_timestamp, current_timestamp, 1, 1),
        (200, 'San Francisco de Maturín', current_timestamp, current_timestamp, 1, 1),
        (201, 'Aguasay', current_timestamp, current_timestamp, 1, 1),
        (202, 'Caripito', current_timestamp, current_timestamp, 1, 1),
        (203, 'El Guácharo', current_timestamp, current_timestamp, 1, 1),
        (203, 'Caripe', current_timestamp, current_timestamp, 1, 1),
        (204, 'Capital Cedeño', current_timestamp, current_timestamp, 1, 1),
        (204, 'San Félix de Cantalicio', current_timestamp, current_timestamp, 1, 1),
        (205, 'El Tejero', current_timestamp, current_timestamp, 1, 1),
        (205, 'Punta de Mata', current_timestamp, current_timestamp, 1, 1),
        (206, 'Chaguaramas', current_timestamp, current_timestamp, 1, 1),
        (206, 'Temblador', current_timestamp, current_timestamp, 1, 1),
        (207, 'Alto de los Godos', current_timestamp, current_timestamp, 1, 1),
        (207, 'Boquerón', current_timestamp, current_timestamp, 1, 1),
        (207, 'Las Cocuizas', current_timestamp, current_timestamp, 1, 1),
        (207, 'La Cruz', current_timestamp, current_timestamp, 1, 1),
        (207, 'San Simón', current_timestamp, current_timestamp, 1, 1),
        (207, 'El Corozo', current_timestamp, current_timestamp, 1, 1),
        (207, 'El Furrial', current_timestamp, current_timestamp, 1, 1),
        (207, 'Jusepín', current_timestamp, current_timestamp, 1, 1),
        (207, 'La Pica', current_timestamp, current_timestamp, 1, 1),
        (207, 'San Vicente', current_timestamp, current_timestamp, 1, 1),
        (208, 'Aparicio', current_timestamp, current_timestamp, 1, 1),
        (208, 'Chaguamal', current_timestamp, current_timestamp, 1, 1),
        (208, 'El Pinto', current_timestamp, current_timestamp, 1, 1),
        (208, 'Guanaguana', current_timestamp, current_timestamp, 1, 1),
        (208, 'La Toscana', current_timestamp, current_timestamp, 1, 1),
        (209, 'Cachipo', current_timestamp, current_timestamp, 1, 1),
        (209, 'Quiriquire', current_timestamp, current_timestamp, 1, 1),
        (210, 'Santa Bárbara', current_timestamp, current_timestamp, 1, 1),
        (211, 'Barrancas', current_timestamp, current_timestamp, 1, 1),
        (212, 'Uracoa', current_timestamp, current_timestamp, 1, 1),
        (213, 'Antolín del Campo', current_timestamp, current_timestamp, 1, 1),
        (214, 'Arismendi', current_timestamp, current_timestamp, 1, 1),
        (215, 'San Juan Bautista', current_timestamp, current_timestamp, 1, 1),
        (215, 'Zabala', current_timestamp, current_timestamp, 1, 1),
        (216, 'García', current_timestamp, current_timestamp, 1, 1),
        (216, 'Francisco Fajardo', current_timestamp, current_timestamp, 1, 1),
        (217, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (217, 'Guevara', current_timestamp, current_timestamp, 1, 1),
        (217, 'Cerro de Matasiete', current_timestamp, current_timestamp, 1, 1),
        (217, 'Santa Ana', current_timestamp, current_timestamp, 1, 1),
        (217, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (218, 'Aguirre', current_timestamp, current_timestamp, 1, 1),
        (218, 'Maneiro', current_timestamp, current_timestamp, 1, 1),
        (219, 'Adrián', current_timestamp, current_timestamp, 1, 1),
        (219, 'Juan Griego', current_timestamp, current_timestamp, 1, 1),
        (219, 'Yaguaraparo', current_timestamp, current_timestamp, 1, 1),
        (220, 'Porlamar', current_timestamp, current_timestamp, 1, 1),
        (221, 'San Francisco de Macanao', current_timestamp, current_timestamp, 1, 1),
        (221, 'Boca de Río', current_timestamp, current_timestamp, 1, 1),
        (222, 'Tubores', current_timestamp, current_timestamp, 1, 1),
        (223, 'Villalba', current_timestamp, current_timestamp, 1, 1),
        (224, 'Agua Blanca', current_timestamp, current_timestamp, 1, 1),
        (225, 'Araure', current_timestamp, current_timestamp, 1, 1),
        (226, 'Píritu', current_timestamp, current_timestamp, 1, 1),
        (226, 'Uveral', current_timestamp, current_timestamp, 1, 1),
        (227, 'Guanare', current_timestamp, current_timestamp, 1, 1),
        (228, 'Guanarito', current_timestamp, current_timestamp, 1, 1),
        (229, 'Peña Blanca', current_timestamp, current_timestamp, 1, 1),
        (230, 'Aparición', current_timestamp, current_timestamp, 1, 1),
        (230, 'Ospino', current_timestamp, current_timestamp, 1, 1),
        (231, 'Acarigua', current_timestamp, current_timestamp, 1, 1),
        (231, 'Payara', current_timestamp, current_timestamp, 1, 1),
        (232, 'Papelón', current_timestamp, current_timestamp, 1, 1),
        (233, 'Boconoíto', current_timestamp, current_timestamp, 1, 1),
        (234, 'San Rafael de Onoto', current_timestamp, current_timestamp, 1, 1),
        (234, 'Santa Fé', current_timestamp, current_timestamp, 1, 1),
        (235, 'Florida', current_timestamp, current_timestamp, 1, 1),
        (235, 'El Playón', current_timestamp, current_timestamp, 1, 1),
        (236, 'Biscucuy', current_timestamp, current_timestamp, 1, 1),
        (236, 'Concepción', current_timestamp, current_timestamp, 1, 1),
        (236, 'San José de Saguaz', current_timestamp, current_timestamp, 1, 1),
        (236, 'San Rafael de Palo Alzado', current_timestamp, current_timestamp, 1, 1),
        (236, 'Uvencio Antonio Velásquez', current_timestamp, current_timestamp, 1, 1),
        (236, 'Villa Rosa', current_timestamp, current_timestamp, 1, 1),
        (237, 'Canelones', current_timestamp, current_timestamp, 1, 1),
        (237, 'Santa Cruz', current_timestamp, current_timestamp, 1, 1),
        (237, 'San Isidro Labrador', current_timestamp, current_timestamp, 1, 1),
        (238, 'Mariño', current_timestamp, current_timestamp, 1, 1);",
        "INSERT INTO parishes
        (town_id, `desc`, created_at, updated_at, created_by, updated_by)
        VALUES
        (238, 'Rómulo Gallegos', current_timestamp, current_timestamp, 1, 1),
        (239, 'San José de Aerocuar', current_timestamp, current_timestamp, 1, 1),
        (239, 'Tavera Acosta', current_timestamp, current_timestamp, 1, 1),
        (240, 'Río Caribe', current_timestamp, current_timestamp, 1, 1),
        (240, 'Antonio José de Sucre', current_timestamp, current_timestamp, 1, 1),
        (240, 'El Morro de Puerto Santo', current_timestamp, current_timestamp, 1, 1),
        (240, 'Puerto Santo', current_timestamp, current_timestamp, 1, 1),
        (240, 'San Juan de las Galdonas', current_timestamp, current_timestamp, 1, 1),
        (241, 'El Pilar', current_timestamp, current_timestamp, 1, 1),
        (241, 'El Rincón', current_timestamp, current_timestamp, 1, 1),
        (241, 'General Francisco Antonio Váquez', current_timestamp, current_timestamp, 1, 1),
        (241, 'Guaraúnos', current_timestamp, current_timestamp, 1, 1),
        (241, 'Tunapuicito', current_timestamp, current_timestamp, 1, 1),
        (241, 'Unión', current_timestamp, current_timestamp, 1, 1),
        (242, 'Santa Catalina', current_timestamp, current_timestamp, 1, 1),
        (242, 'Santa Rosa', current_timestamp, current_timestamp, 1, 1),
        (242, 'Santa Teresa', current_timestamp, current_timestamp, 1, 1),
        (242, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (242, 'Maracapana', current_timestamp, current_timestamp, 1, 1),
        (243, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (244, 'El Paujil', current_timestamp, current_timestamp, 1, 1),
        (245, 'Cruz Salmerón Acosta', current_timestamp, current_timestamp, 1, 1),
        (245, 'Manicuare', current_timestamp, current_timestamp, 1, 1),
        (246, 'Tunapuy', current_timestamp, current_timestamp, 1, 1),
        (246, 'Campo Elías', current_timestamp, current_timestamp, 1, 1),
        (247, 'Irapa', current_timestamp, current_timestamp, 1, 1),
        (247, 'Campo Claro', current_timestamp, current_timestamp, 1, 1),
        (247, 'Maraval', current_timestamp, current_timestamp, 1, 1),
        (247, 'Soro', current_timestamp, current_timestamp, 1, 1),
        (248, 'Mejía', current_timestamp, current_timestamp, 1, 1),
        (249, 'Cumanacoa', current_timestamp, current_timestamp, 1, 1),
        (249, 'Aricagua', current_timestamp, current_timestamp, 1, 1),
        (249, 'San Fernando', current_timestamp, current_timestamp, 1, 1),
        (249, 'San Lorenzo', current_timestamp, current_timestamp, 1, 1),
        (250, 'Villa Frontado', current_timestamp, current_timestamp, 1, 1),
        (250, 'Catuaro', current_timestamp, current_timestamp, 1, 1),
        (250, 'Rendón', current_timestamp, current_timestamp, 1, 1),
        (250, 'San Cruz', current_timestamp, current_timestamp, 1, 1),
        (250, 'Santa María', current_timestamp, current_timestamp, 1, 1),
        (251, 'Altagracia', current_timestamp, current_timestamp, 1, 1),
        (251, 'Santa Inés', current_timestamp, current_timestamp, 1, 1),
        (251, 'Valentín Valiente', current_timestamp, current_timestamp, 1, 1),
        (251, 'Ayacucho', current_timestamp, current_timestamp, 1, 1),
        (251, 'San Juan', current_timestamp, current_timestamp, 1, 1),
        (251, 'Raúl Leoni', current_timestamp, current_timestamp, 1, 1),
        (251, 'Gran Mariscal', current_timestamp, current_timestamp, 1, 1),
        (252, 'Cristóbal Colón', current_timestamp, current_timestamp, 1, 1),
        (252, 'Bideau', current_timestamp, current_timestamp, 1, 1),
        (252, 'Punta de Piedras', current_timestamp, current_timestamp, 1, 1),
        (252, 'Güiria', current_timestamp, current_timestamp, 1, 1),
        (253, 'Andrés Bello', current_timestamp, current_timestamp, 1, 1),
        (254, 'Antonio Rómulo Costa', current_timestamp, current_timestamp, 1, 1),
        (255, 'Ayacucho', current_timestamp, current_timestamp, 1, 1),
        (255, 'San Pedro del Río', current_timestamp, current_timestamp, 1, 1),
        (256, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (257, 'Cárdenas', current_timestamp, current_timestamp, 1, 1),
        (258, 'Córdoba', current_timestamp, current_timestamp, 1, 1),
        (259, 'Fernández Feo', current_timestamp, current_timestamp, 1, 1),
        (259, 'Alberto Adriani', current_timestamp, current_timestamp, 1, 1),
        (260, 'Francisco de Miranda', current_timestamp, current_timestamp, 1, 1),
        (261, 'García de Hevia', current_timestamp, current_timestamp, 1, 1),
        (261, 'Boca de Grita', current_timestamp, current_timestamp, 1, 1),
        (262, 'Guásimos', current_timestamp, current_timestamp, 1, 1),
        (263, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (262, 'Juan Germán Roscio', current_timestamp, current_timestamp, 1, 1),
        (264, 'Jáuregui', current_timestamp, current_timestamp, 1, 1),
        (265, 'José María Vargas', current_timestamp, current_timestamp, 1, 1),
        (266, 'Junín', current_timestamp, current_timestamp, 1, 1),
        (266, 'La Petrólea', current_timestamp, current_timestamp, 1, 1),
        (267, 'Libertad', current_timestamp, current_timestamp, 1, 1),
        (268, 'Capital Libertador', current_timestamp, current_timestamp, 1, 1),
        (269, 'Lobatera', current_timestamp, current_timestamp, 1, 1),
        (270, 'Michelena', current_timestamp, current_timestamp, 1, 1),
        (271, 'Panamericano', current_timestamp, current_timestamp, 1, 1),
        (272, 'Pedro María Ureña', current_timestamp, current_timestamp, 1, 1),
        (273, 'Delicias', current_timestamp, current_timestamp, 1, 1),
        (274, 'Samuel Darío Maldonado', current_timestamp, current_timestamp, 1, 1),
        (274, 'Boconó', current_timestamp, current_timestamp, 1, 1),
        (275, 'La Concordia', current_timestamp, current_timestamp, 1, 1),
        (275, 'San Juan Bautista', current_timestamp, current_timestamp, 1, 1),
        (275, 'Pedro María Morantes', current_timestamp, current_timestamp, 1, 1),
        (276, 'Seboruco', current_timestamp, current_timestamp, 1, 1),
        (277, 'Simón Rodríguez', current_timestamp, current_timestamp, 1, 1),
        (278, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (279, 'San José', current_timestamp, current_timestamp, 1, 1),
        (280, 'Uribante', current_timestamp, current_timestamp, 1, 1),
        (280, 'Juan Pablo Peñalosa', current_timestamp, current_timestamp, 1, 1),
        (280, 'Potosí', current_timestamp, current_timestamp, 1, 1),
        (281, 'San Judas Tadeo', current_timestamp, current_timestamp, 1, 1),
        (282, 'Araguaney', current_timestamp, current_timestamp, 1, 1),
        (282, 'El Jaguito', current_timestamp, current_timestamp, 1, 1),
        (283, 'Boconó', current_timestamp, current_timestamp, 1, 1),
        (284, 'Sabana Grande', current_timestamp, current_timestamp, 1, 1),
        (284, 'Cheregüé', current_timestamp, current_timestamp, 1, 1),
        (285, 'Arnoldo Gabaldón', current_timestamp, current_timestamp, 1, 1),
        (285, 'Bolivia', current_timestamp, current_timestamp, 1, 1),
        (285, 'Carrillo', current_timestamp, current_timestamp, 1, 1),
        (285, 'Manuel Salvador Ulloa', current_timestamp, current_timestamp, 1, 1),
        (286, 'Carache', current_timestamp, current_timestamp, 1, 1),
        (286, 'La Concepción', current_timestamp, current_timestamp, 1, 1),
        (286, 'Santa Cruz', current_timestamp, current_timestamp, 1, 1),
        (287, 'Escuque', current_timestamp, current_timestamp, 1, 1),
        (287, 'Santa Rita', current_timestamp, current_timestamp, 1, 1),
        (288, 'El Socorro', current_timestamp, current_timestamp, 1, 1),
        (288, 'Antonio José de Sucre', current_timestamp, current_timestamp, 1, 1),
        (289, 'Campo Elías', current_timestamp, current_timestamp, 1, 1),
        (289, 'Arnoldo Gabaldón', current_timestamp, current_timestamp, 1, 1),
        (290, 'Santa Apolonia', current_timestamp, current_timestamp, 1, 1),
        (290, 'La Ceiba', current_timestamp, current_timestamp, 1, 1),
        (291, 'Agua Santa', current_timestamp, current_timestamp, 1, 1),
        (291, 'Valerita', current_timestamp, current_timestamp, 1, 1),
        (292, 'Carmelo', current_timestamp, current_timestamp, 1, 1),
        (292, 'Santa María del Horcón', current_timestamp, current_timestamp, 1, 1),
        (293, 'Motatán', current_timestamp, current_timestamp, 1, 1),
        (293, 'Jalisco', current_timestamp, current_timestamp, 1, 1),
        (294, 'Pampán', current_timestamp, current_timestamp, 1, 1),
        (294, 'Santa Ana', current_timestamp, current_timestamp, 1, 1),
        (295, 'Pampanito', current_timestamp, current_timestamp, 1, 1),
        (295, 'Pampanito II', current_timestamp, current_timestamp, 1, 1),
        (296, 'Betijoque', current_timestamp, current_timestamp, 1, 1),
        (296, 'José Gregorio Hernández', current_timestamp, current_timestamp, 1, 1),
        (296, 'La Pueblita', current_timestamp, current_timestamp, 1, 1),
        (297, 'Carvajal', current_timestamp, current_timestamp, 1, 1),
        (297, 'Campo Alegre', current_timestamp, current_timestamp, 1, 1),
        (297, 'Antonio Nicolás Briceño', current_timestamp, current_timestamp, 1, 1),
        (298, 'Sabana de Mendoza', current_timestamp, current_timestamp, 1, 1),
        (298, 'Junín', current_timestamp, current_timestamp, 1, 1),
        (298, 'Valmore Rodríguez', current_timestamp, current_timestamp, 1, 1),
        (298, 'El Paraíso', current_timestamp, current_timestamp, 1, 1),
        (299, 'Andrés Linares', current_timestamp, current_timestamp, 1, 1),
        (299, 'Cristóbal Mendoza', current_timestamp, current_timestamp, 1, 1),
        (299, 'Carrillo', current_timestamp, current_timestamp, 1, 1),
        (300, 'Cabimbú', current_timestamp, current_timestamp, 1, 1),
        (300, 'Jajó', current_timestamp, current_timestamp, 1, 1),
        (300, 'La Mesa de Esnujaque', current_timestamp, current_timestamp, 1, 1),
        (300, 'Santiago', current_timestamp, current_timestamp, 1, 1),
        (300, 'La Quebrada', current_timestamp, current_timestamp, 1, 1),
        (301, 'Juan Ignacio Montilla', current_timestamp, current_timestamp, 1, 1),
        (301, 'La Beatriz', current_timestamp, current_timestamp, 1, 1),
        (301, 'La Puerta', current_timestamp, current_timestamp, 1, 1),
        (301, 'Mendoza del Valle de Momboy', current_timestamp, current_timestamp, 1, 1),
        (301, 'Mercedes Díaz', current_timestamp, current_timestamp, 1, 1),
        (301, 'San Luis', current_timestamp, current_timestamp, 1, 1),
        (302, 'El Guayabo', current_timestamp, current_timestamp, 1, 1),
        (302, 'Farriar', current_timestamp, current_timestamp, 1, 1),
        (303, 'Arístides Bastidas', current_timestamp, current_timestamp, 1, 1),
        (304, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (305, 'Chivacoa', current_timestamp, current_timestamp, 1, 1),
        (305, 'Campo Elías', current_timestamp, current_timestamp, 1, 1),
        (306, 'Cocorote', current_timestamp, current_timestamp, 1, 1),
        (307, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (308, 'José Antonio Páez', current_timestamp, current_timestamp, 1, 1),
        (309, 'La Trinidad', current_timestamp, current_timestamp, 1, 1),
        (310, 'Manuel Monge', current_timestamp, current_timestamp, 1, 1),
        (311, 'Salóm', current_timestamp, current_timestamp, 1, 1),
        (311, 'Nirgua', current_timestamp, current_timestamp, 1, 1),
        (312, 'San Andrés', current_timestamp, current_timestamp, 1, 1),
        (312, 'Yaritagua', current_timestamp, current_timestamp, 1, 1),
        (313, 'San Felipe', current_timestamp, current_timestamp, 1, 1),
        (313, 'San Javier', current_timestamp, current_timestamp, 1, 1),
        (314, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (315, 'Urachiche', current_timestamp, current_timestamp, 1, 1),
        (316, 'Isla de Toas', current_timestamp, current_timestamp, 1, 1),
        (316, 'Monagas', current_timestamp, current_timestamp, 1, 1),
        (317, 'San Timoteo', current_timestamp, current_timestamp, 1, 1),
        (317, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (317, 'Pueblo Nuevo', current_timestamp, current_timestamp, 1, 1),
        (318, 'La Rosa', current_timestamp, current_timestamp, 1, 1),
        (318, 'Rómulo Betancourt', current_timestamp, current_timestamp, 1, 1),
        (318, 'San Benito', current_timestamp, current_timestamp, 1, 1),
        (318, 'Arístides Calvani', current_timestamp, current_timestamp, 1, 1),
        (319, 'Encontrados', current_timestamp, current_timestamp, 1, 1),
        (320, 'Moralito', current_timestamp, current_timestamp, 1, 1),
        (320, 'San Carlos del Zulia', current_timestamp, current_timestamp, 1, 1),
        (320, 'Santa Cruz del Zulia', current_timestamp, current_timestamp, 1, 1),
        (320, 'Santa Bárbara', current_timestamp, current_timestamp, 1, 1),
        (320, 'Urribarrí', current_timestamp, current_timestamp, 1, 1),
        (321, 'Carlos Quevedo', current_timestamp, current_timestamp, 1, 1),
        (321, 'Francisco Javier Pulgar', current_timestamp, current_timestamp, 1, 1),
        (322, 'La Concepción', current_timestamp, current_timestamp, 1, 1),
        (322, 'Mariano Parra León', current_timestamp, current_timestamp, 1, 1),
        (323, 'Concepción', current_timestamp, current_timestamp, 1, 1),
        (323, 'Chiquinquirá', current_timestamp, current_timestamp, 1, 1),
        (323, 'Potreritos', current_timestamp, current_timestamp, 1, 1),
        (324, 'Libertad', current_timestamp, current_timestamp, 1, 1),
        (324, 'Venezuela', current_timestamp, current_timestamp, 1, 1),
        (324, 'Campo Lara', current_timestamp, current_timestamp, 1, 1),
        (325, 'San José de Perijá', current_timestamp, current_timestamp, 1, 1),
        (326, 'mara', current_timestamp, current_timestamp, 1, 1),
        (327, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (327, 'Coquivacoa', current_timestamp, current_timestamp, 1, 1),
        (327, 'Chiquinquirá', current_timestamp, current_timestamp, 1, 1),
        (327, 'Raúl Leoni', current_timestamp, current_timestamp, 1, 1),
        (327, 'Santa Lucía', current_timestamp, current_timestamp, 1, 1),
        (327, 'San Isidro', current_timestamp, current_timestamp, 1, 1),
        (328, 'Altagracia', current_timestamp, current_timestamp, 1, 1),
        (328, 'Faría', current_timestamp, current_timestamp, 1, 1),
        (328, 'San Antonio', current_timestamp, current_timestamp, 1, 1),
        (328, 'San José', current_timestamp, current_timestamp, 1, 1),
        (329, 'Guajira', current_timestamp, current_timestamp, 1, 1),
        (329, 'Elías Sánchez Rubio', current_timestamp, current_timestamp, 1, 1),
        (330, 'El Rosario', current_timestamp, current_timestamp, 1, 1),
        (331, 'San Francisco', current_timestamp, current_timestamp, 1, 1),
        (331, 'Los Cortijos', current_timestamp, current_timestamp, 1, 1),
        (332, 'Santa Rita', current_timestamp, current_timestamp, 1, 1),
        (332, 'Urribarrí', current_timestamp, current_timestamp, 1, 1),
        (333, 'Rafael', current_timestamp, current_timestamp, 1, 1),
        (333, 'Manuel Manrique', current_timestamp, current_timestamp, 1, 1),
        (334, 'Gibraltar', current_timestamp, current_timestamp, 1, 1),
        (334, 'Rómulo Gallegos', current_timestamp, current_timestamp, 1, 1),
        (335, 'Rafael Urdaneta ', current_timestamp, current_timestamp, 1, 1),
        (334, 'La Victoria', current_timestamp, current_timestamp, 1, 1),
        (335, 'Raúl Cuenca', current_timestamp, current_timestamp, 1, 1),
        (336, 'Jesús María Semprún', current_timestamp, current_timestamp, 1, 1);"
    ];

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->command->comment('Empezando ' . __CLASS__);

        foreach ($this->sql as $statement) {
            DB::statement($statement);
        }
    }
}
