<?php namespace PCI\Database;

use DB;

/**
 * Class TownSeeder
 *
 * @package PCI\Database
 * @author  Alejandro Granadillo <slayerfat@gmail.com>
 * @link    https://github.com/slayerfat/sistemaPCI Repositorio en linea.
 */
class TownSeeder extends AbstractSeeder
{

    /**
     * @param array
     */
    protected $towns = "INSERT INTO towns
        (id, state_id, `desc`, created_at, updated_at, created_by, updated_by)
        VALUES
        (1, 1, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (2, 15, 'Baruta', current_timestamp, current_timestamp, 1, 1),
        (3, 15, 'Chacao', current_timestamp, current_timestamp, 1, 1),
        (4, 15, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (5, 15, 'El Hatillo', current_timestamp, current_timestamp, 1, 1),
        (6, 15, 'Acevedo', current_timestamp, current_timestamp, 1, 1),
        (7, 15, 'Andres Bello', current_timestamp, current_timestamp, 1, 1),
        (8, 15, 'Brion', current_timestamp, current_timestamp, 1, 1),
        (9, 15, 'Buroz', current_timestamp, current_timestamp, 1, 1),
        (10, 15, 'Carrizal', current_timestamp, current_timestamp, 1, 1),
        (11, 15, 'Cristobal Rojas', current_timestamp, current_timestamp, 1, 1),
        (12, 15, 'Guacaipuro', current_timestamp, current_timestamp, 1, 1),
        (13, 15, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (14, 15, 'Lander', current_timestamp, current_timestamp, 1, 1),
        (15, 15, 'Los Salias', current_timestamp, current_timestamp, 1, 1),
        (16, 15, 'Paez', current_timestamp, current_timestamp, 1, 1),
        (17, 15, 'Paz Castillo', current_timestamp, current_timestamp, 1, 1),
        (18, 15, 'Pedro Gual', current_timestamp, current_timestamp, 1, 1),
        (19, 15, 'Plaza', current_timestamp, current_timestamp, 1, 1),
        (20, 15, 'Simon Bolivar', current_timestamp, current_timestamp, 1, 1),
        (21, 15, 'Urdaneta', current_timestamp, current_timestamp, 1, 1),
        (22, 15, 'Zamora', current_timestamp, current_timestamp, 1, 1),
        (23, 23, 'Vargas', current_timestamp, current_timestamp, 1, 1),
        (24, 12, 'Camaguan', current_timestamp, current_timestamp, 1, 1),
        (25, 12, 'Chaguaramas', current_timestamp, current_timestamp, 1, 1),
        (26, 12, 'El Socorro', current_timestamp, current_timestamp, 1, 1),
        (27, 12, 'Francisco de Miranda', current_timestamp, current_timestamp, 1, 1),
        (28, 12, 'Jose Felix Ribas', current_timestamp, current_timestamp, 1, 1),
        (29, 12, 'Jose Tadeo Monagas', current_timestamp, current_timestamp, 1, 1),
        (30, 12, 'Juan German Roscio', current_timestamp, current_timestamp, 1, 1),
        (31, 12, 'Julian Mellado', current_timestamp, current_timestamp, 1, 1),
        (32, 12, 'Las Mercedes del Llano', current_timestamp, current_timestamp, 1, 1),
        (33, 12, 'Leonardo Infante', current_timestamp, current_timestamp, 1, 1),
        (34, 12, 'Ortiz', current_timestamp, current_timestamp, 1, 1),
        (35, 12, 'Pedro Zaraza', current_timestamp, current_timestamp, 1, 1),
        (36, 12, 'San Geronimo de Guayabal', current_timestamp, current_timestamp, 1, 1),
        (37, 12, 'San Jose de Guaribe', current_timestamp, current_timestamp, 1, 1),
        (38, 12, 'Santa Maria de Ipire', current_timestamp, current_timestamp, 1, 1),
        (39, 5, 'Bolivar', current_timestamp, current_timestamp, 1, 1),
        (41, 5, 'Camatagua', current_timestamp, current_timestamp, 1, 1),
        (42, 5, 'Francisco Linares', current_timestamp, current_timestamp, 1, 1),
        (43, 5, 'Giradot', current_timestamp, current_timestamp, 1, 1),
        (44, 5, 'Jose Angel Lamas', current_timestamp, current_timestamp, 1, 1),
        (45, 5, 'Jose Felix Ribas', current_timestamp, current_timestamp, 1, 1),
        (46, 5, 'Jose Revenga', current_timestamp, current_timestamp, 1, 1),
        (47, 5, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (48, 5, 'Mario Iragorry', current_timestamp, current_timestamp, 1, 1),
        (49, 5, 'Ocumare de la costa', current_timestamp, current_timestamp, 1, 1),
        (50, 5, 'San Casimiro', current_timestamp, current_timestamp, 1, 1),
        (51, 5, 'San Sebastian', current_timestamp, current_timestamp, 1, 1),
        (52, 5, 'Santiago Mariño', current_timestamp, current_timestamp, 1, 1),
        (53, 5, 'Santos Michelena', current_timestamp, current_timestamp, 1, 1),
        (54, 5, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (55, 5, 'Tovar', current_timestamp, current_timestamp, 1, 1),
        (56, 5, 'Urdaneta', current_timestamp, current_timestamp, 1, 1),
        (57, 5, 'Zamora', current_timestamp, current_timestamp, 1, 1),
        (58, 8, 'Bejuma', current_timestamp, current_timestamp, 1, 1),
        (59, 8, 'Carlos Arevalo', current_timestamp, current_timestamp, 1, 1),
        (60, 8, 'Diego Ibarra', current_timestamp, current_timestamp, 1, 1),
        (61, 8, 'Guacara', current_timestamp, current_timestamp, 1, 1),
        (62, 8, 'Juan Jose Mora', current_timestamp, current_timestamp, 1, 1),
        (63, 8, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (64, 8, 'Los Guayos', current_timestamp, current_timestamp, 1, 1),
        (65, 8, 'Miranda', current_timestamp, current_timestamp, 1, 1),
        (66, 8, 'Montalban', current_timestamp, current_timestamp, 1, 1),
        (67, 8, 'Naguanagua', current_timestamp, current_timestamp, 1, 1),
        (68, 8, 'Puerto Cabello', current_timestamp, current_timestamp, 1, 1),
        (69, 8, 'San Diego', current_timestamp, current_timestamp, 1, 1),
        (70, 8, 'San Joaquin', current_timestamp, current_timestamp, 1, 1),
        (71, 8, 'Valencia', current_timestamp, current_timestamp, 1, 1),
        (72, 2, 'Anaco', current_timestamp, current_timestamp, 1, 1),
        (73, 2, 'Aragua', current_timestamp, current_timestamp, 1, 1),
        (74, 2, 'Bolivar', current_timestamp, current_timestamp, 1, 1),
        (75, 2, 'Bruzual', current_timestamp, current_timestamp, 1, 1),
        (76, 2, 'Cajigal', current_timestamp, current_timestamp, 1, 1),
        (77, 2, 'Carvajal', current_timestamp, current_timestamp, 1, 1),
        (78, 2, 'Diego Bautista Urbaneja', current_timestamp, current_timestamp, 1, 1),
        (79, 2, 'Freites', current_timestamp, current_timestamp, 1, 1),
        (80, 2, 'Guanipa', current_timestamp, current_timestamp, 1, 1),
        (81, 2, 'Guanta', current_timestamp, current_timestamp, 1, 1),
        (82, 2, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (83, 2, 'Libertad', current_timestamp, current_timestamp, 1, 1),
        (84, 2, 'Mcgregor', current_timestamp, current_timestamp, 1, 1),
        (85, 2, 'Miranda', current_timestamp, current_timestamp, 1, 1),
        (86, 2, 'Monagas', current_timestamp, current_timestamp, 1, 1),
        (87, 2, 'Peñalver', current_timestamp, current_timestamp, 1, 1),
        (88, 2, 'Piritu', current_timestamp, current_timestamp, 1, 1),
        (89, 2, 'San Juan de Capistrano', current_timestamp, current_timestamp, 1, 1),
        (90, 2, 'Santa Ana', current_timestamp, current_timestamp, 1, 1),
        (91, 2, 'Simón Rodriguez', current_timestamp, current_timestamp, 1, 1),
        (92, 2, 'Sotillo', current_timestamp, current_timestamp, 1, 1),
        (93, 3, 'Alto Orinoco', current_timestamp, current_timestamp, 1, 1),
        (94, 3, 'Atabapo', current_timestamp, current_timestamp, 1, 1),
        (95, 3, 'Atures', current_timestamp, current_timestamp, 1, 1),
        (96, 3, 'Autana', current_timestamp, current_timestamp, 1, 1),
        (97, 3, 'Manapiare', current_timestamp, current_timestamp, 1, 1),
        (98, 3, 'Maroa', current_timestamp, current_timestamp, 1, 1),
        (99, 3, 'Rio Negro', current_timestamp, current_timestamp, 1, 1),
        (100, 4, 'Achaguas', current_timestamp, current_timestamp, 1, 1),
        (101, 4, 'Biruaca', current_timestamp, current_timestamp, 1, 1),
        (102, 4, 'Muños', current_timestamp, current_timestamp, 1, 1),
        (103, 4, 'Paez', current_timestamp, current_timestamp, 1, 1),
        (104, 4, 'Pedro Camejo', current_timestamp, current_timestamp, 1, 1),
        (105, 4, 'Romulo Gallegos', current_timestamp, current_timestamp, 1, 1),
        (106, 4, 'San Fernando', current_timestamp, current_timestamp, 1, 1),
        (107, 6, 'Alberto Arvelo Torrealba', current_timestamp, current_timestamp, 1, 1),
        (108, 6, 'Andrés Eloy Blanco', current_timestamp, current_timestamp, 1, 1),
        (109, 6, 'Antonio José de Sucre', current_timestamp, current_timestamp, 1, 1),
        (110, 6, 'Arismendi', current_timestamp, current_timestamp, 1, 1),
        (111, 6, 'Barinas', current_timestamp, current_timestamp, 1, 1),
        (112, 6, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (113, 6, 'Cruz Paredes', current_timestamp, current_timestamp, 1, 1),
        (114, 6, 'Ezequiel Zamora', current_timestamp, current_timestamp, 1, 1),
        (115, 6, 'Obispos', current_timestamp, current_timestamp, 1, 1),
        (116, 6, 'Pedraza', current_timestamp, current_timestamp, 1, 1),
        (117, 6, 'Rojas', current_timestamp, current_timestamp, 1, 1),
        (118, 6, 'Sosa', current_timestamp, current_timestamp, 1, 1),
        (119, 7, 'Caroní', current_timestamp, current_timestamp, 1, 1),
        (120, 7, 'Cedeño', current_timestamp, current_timestamp, 1, 1),
        (121, 7, 'El Callao', current_timestamp, current_timestamp, 1, 1),
        (122, 7, 'Gran Sabana', current_timestamp, current_timestamp, 1, 1),
        (123, 7, 'Heres', current_timestamp, current_timestamp, 1, 1),
        (124, 7, 'Piar', current_timestamp, current_timestamp, 1, 1),
        (125, 7, 'Raul Leoni', current_timestamp, current_timestamp, 1, 1),
        (126, 7, 'Roscio', current_timestamp, current_timestamp, 1, 1),
        (127, 7, 'Sifontes', current_timestamp, current_timestamp, 1, 1),
        (128, 7, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (129, 7, 'Padre Pedro Chen', current_timestamp, current_timestamp, 1, 1),
        (130, 9, 'Anzoategui', current_timestamp, current_timestamp, 1, 1),
        (131, 9, 'Falcon', current_timestamp, current_timestamp, 1, 1),
        (132, 9, 'Giraldot', current_timestamp, current_timestamp, 1, 1),
        (133, 9, 'Lima Blanco', current_timestamp, current_timestamp, 1, 1),
        (134, 9, 'Pao de San Juan Bautista', current_timestamp, current_timestamp, 1, 1),
        (135, 9, 'Ricaurte', current_timestamp, current_timestamp, 1, 1),
        (136, 9, 'Rómulo Gallegos', current_timestamp, current_timestamp, 1, 1),
        (137, 9, 'San Carlos', current_timestamp, current_timestamp, 1, 1),
        (138, 9, 'Tinaco', current_timestamp, current_timestamp, 1, 1),
        (139, 10, 'Antonio Díaz', current_timestamp, current_timestamp, 1, 1),
        (140, 10, 'Casacoima', current_timestamp, current_timestamp, 1, 1),
        (141, 10, 'Pedernales', current_timestamp, current_timestamp, 1, 1),
        (142, 10, 'Tucupita', current_timestamp, current_timestamp, 1, 1),
        (143, 11, 'Acosta', current_timestamp, current_timestamp, 1, 1),
        (144, 11, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (145, 11, 'Buchivacoa', current_timestamp, current_timestamp, 1, 1),
        (146, 11, 'Cacique Manaure', current_timestamp, current_timestamp, 1, 1),
        (147, 11, 'Carirubana', current_timestamp, current_timestamp, 1, 1),
        (148, 11, 'Colina', current_timestamp, current_timestamp, 1, 1),
        (149, 11, 'Dabajuro', current_timestamp, current_timestamp, 1, 1),
        (150, 11, 'Democracia', current_timestamp, current_timestamp, 1, 1),
        (151, 11, 'Falcón', current_timestamp, current_timestamp, 1, 1),
        (152, 11, 'Federacion', current_timestamp, current_timestamp, 1, 1),
        (153, 11, 'Jacura', current_timestamp, current_timestamp, 1, 1),
        (154, 11, 'Los Taques', current_timestamp, current_timestamp, 1, 1),
        (155, 11, 'Mauroa', current_timestamp, current_timestamp, 1, 1),
        (156, 11, 'Miranda', current_timestamp, current_timestamp, 1, 1),
        (157, 11, 'Monseñor Iturriza', current_timestamp, current_timestamp, 1, 1),
        (158, 11, 'Palmasola', current_timestamp, current_timestamp, 1, 1),
        (159, 11, 'Petit', current_timestamp, current_timestamp, 1, 1),
        (160, 11, 'Piritu', current_timestamp, current_timestamp, 1, 1),
        (161, 11, 'San Francisco', current_timestamp, current_timestamp, 1, 1),
        (162, 11, 'Silva', current_timestamp, current_timestamp, 1, 1),
        (163, 11, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (164, 11, 'Tocopero', current_timestamp, current_timestamp, 1, 1),
        (165, 11, 'Union', current_timestamp, current_timestamp, 1, 1),
        (166, 11, 'Urumaco', current_timestamp, current_timestamp, 1, 1),
        (167, 11, 'Zamora', current_timestamp, current_timestamp, 1, 1),
        (168, 13, 'Andrés Eloy Blanco', current_timestamp, current_timestamp, 1, 1),
        (169, 13, 'Crespo', current_timestamp, current_timestamp, 1, 1),
        (170, 13, 'Iribarren', current_timestamp, current_timestamp, 1, 1),
        (171, 13, 'Jiménez', current_timestamp, current_timestamp, 1, 1),
        (172, 13, 'Morán', current_timestamp, current_timestamp, 1, 1),
        (173, 13, 'Palavecino', current_timestamp, current_timestamp, 1, 1),
        (174, 13, 'Simón Planas', current_timestamp, current_timestamp, 1, 1),
        (175, 13, 'Torres', current_timestamp, current_timestamp, 1, 1),
        (176, 13, 'Urdaneta', current_timestamp, current_timestamp, 1, 1),
        (177, 14, 'Alberto Adriani', current_timestamp, current_timestamp, 1, 1),
        (178, 14, 'Andrés Bello ', current_timestamp, current_timestamp, 1, 1),
        (179, 14, 'Antonio Pinto Salinas ', current_timestamp, current_timestamp, 1, 1),
        (180, 14, 'Acarigua', current_timestamp, current_timestamp, 1, 1),
        (181, 14, 'Arzobispo Chacón', current_timestamp, current_timestamp, 1, 1),
        (182, 14, 'Campo Elías', current_timestamp, current_timestamp, 1, 1),
        (183, 14, 'Caracciolo Parra Olmedo ', current_timestamp, current_timestamp, 1, 1),
        (184, 14, 'Cardenal Quintero', current_timestamp, current_timestamp, 1, 1),
        (185, 14, 'Guaraque', current_timestamp, current_timestamp, 1, 1),
        (186, 14, 'Julio César Salas ', current_timestamp, current_timestamp, 1, 1),
        (187, 14, 'Justo Briceño', current_timestamp, current_timestamp, 1, 1),
        (188, 14, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (189, 14, 'Miranda', current_timestamp, current_timestamp, 1, 1),
        (190, 14, 'Obispo Ramos de Lora ', current_timestamp, current_timestamp, 1, 1),
        (191, 14, 'Padre Norega', current_timestamp, current_timestamp, 1, 1),
        (192, 14, 'Pueblo Llano', current_timestamp, current_timestamp, 1, 1),
        (193, 14, 'Rangel', current_timestamp, current_timestamp, 1, 1),
        (194, 14, 'Rivas Dávila', current_timestamp, current_timestamp, 1, 1),
        (195, 14, 'Santos Marquina', current_timestamp, current_timestamp, 1, 1),
        (196, 14, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (197, 14, 'Tovar', current_timestamp, current_timestamp, 1, 1),
        (198, 14, 'Tulio Febres Cordero', current_timestamp, current_timestamp, 1, 1),
        (199, 14, 'Zea', current_timestamp, current_timestamp, 1, 1),
        (200, 16, 'Acosta', current_timestamp, current_timestamp, 1, 1),
        (201, 16, 'Aguasay', current_timestamp, current_timestamp, 1, 1),
        (202, 16, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (203, 16, 'Caripe', current_timestamp, current_timestamp, 1, 1),
        (204, 16, 'Cedeño', current_timestamp, current_timestamp, 1, 1),
        (205, 16, 'Ezequiel Zamora', current_timestamp, current_timestamp, 1, 1),
        (206, 16, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (207, 16, 'Maturín', current_timestamp, current_timestamp, 1, 1),
        (208, 16, 'Piar', current_timestamp, current_timestamp, 1, 1),
        (209, 16, 'Punceres', current_timestamp, current_timestamp, 1, 1),
        (210, 16, 'Santa Bárbara', current_timestamp, current_timestamp, 1, 1),
        (211, 16, 'Sotillo', current_timestamp, current_timestamp, 1, 1),
        (212, 16, 'Uracoa', current_timestamp, current_timestamp, 1, 1),
        (213, 17, 'Antolín del Campo', current_timestamp, current_timestamp, 1, 1),
        (214, 17, 'Arismendi', current_timestamp, current_timestamp, 1, 1),
        (215, 17, 'Díaz', current_timestamp, current_timestamp, 1, 1),
        (216, 17, 'García', current_timestamp, current_timestamp, 1, 1),
        (217, 17, 'Gómez', current_timestamp, current_timestamp, 1, 1),
        (218, 17, 'Maneiro', current_timestamp, current_timestamp, 1, 1),
        (219, 17, 'Marcano', current_timestamp, current_timestamp, 1, 1),
        (220, 17, 'Mariño', current_timestamp, current_timestamp, 1, 1),
        (221, 17, 'Península de Macanao', current_timestamp, current_timestamp, 1, 1),
        (222, 17, 'Tubores', current_timestamp, current_timestamp, 1, 1),
        (223, 17, 'Villalba', current_timestamp, current_timestamp, 1, 1),
        (224, 18, 'Agua Blanca', current_timestamp, current_timestamp, 1, 1),
        (225, 18, 'Araure', current_timestamp, current_timestamp, 1, 1),
        (226, 18, 'Esteller', current_timestamp, current_timestamp, 1, 1),
        (227, 18, 'Guanare', current_timestamp, current_timestamp, 1, 1),
        (228, 18, 'Guanarito', current_timestamp, current_timestamp, 1, 1),
        (229, 18, 'Monseñor José Vicenti de Unda', current_timestamp, current_timestamp, 1, 1),
        (230, 18, 'Ospino', current_timestamp, current_timestamp, 1, 1),
        (231, 18, 'Páez', current_timestamp, current_timestamp, 1, 1),
        (232, 18, 'Papelón', current_timestamp, current_timestamp, 1, 1),
        (233, 18, 'San Genaro de Boconoíto', current_timestamp, current_timestamp, 1, 1),
        (234, 18, 'San Rafael de Onoto', current_timestamp, current_timestamp, 1, 1),
        (235, 18, 'Santa Rosalía', current_timestamp, current_timestamp, 1, 1),
        (236, 18, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (237, 18, 'Turén', current_timestamp, current_timestamp, 1, 1),
        (238, 19, 'Andrés Eloy Blanco19', current_timestamp, current_timestamp, 1, 1),
        (239, 19, 'Andrés Mata', current_timestamp, current_timestamp, 1, 1),
        (240, 19, 'Arismendi', current_timestamp, current_timestamp, 1, 1),
        (241, 19, 'Benítez', current_timestamp, current_timestamp, 1, 1),
        (242, 19, 'Beremúdez', current_timestamp, current_timestamp, 1, 1),
        (243, 19, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (244, 19, 'Cagigal', current_timestamp, current_timestamp, 1, 1),
        (245, 19, 'Cruz Salmerón Acosta', current_timestamp, current_timestamp, 1, 1),
        (246, 19, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (247, 19, 'Mariño', current_timestamp, current_timestamp, 1, 1),
        (248, 19, 'Mejía', current_timestamp, current_timestamp, 1, 1),
        (249, 19, 'Montes', current_timestamp, current_timestamp, 1, 1),
        (250, 19, 'Ribero', current_timestamp, current_timestamp, 1, 1),
        (251, 19, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (252, 19, 'Valdez', current_timestamp, current_timestamp, 1, 1),
        (253, 20, 'Andrés Bello', current_timestamp, current_timestamp, 1, 1),
        (254, 20, 'Antonio Rómulo Costa', current_timestamp, current_timestamp, 1, 1),
        (255, 20, 'Ayacucho', current_timestamp, current_timestamp, 1, 1),
        (256, 20, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (257, 20, 'Cárdenas', current_timestamp, current_timestamp, 1, 1),
        (258, 20, 'Córdova', current_timestamp, current_timestamp, 1, 1),
        (259, 20, 'Fernández Feo', current_timestamp, current_timestamp, 1, 1),
        (260, 20, 'Francisco de Miranda', current_timestamp, current_timestamp, 1, 1),
        (261, 20, 'García de Hevia', current_timestamp, current_timestamp, 1, 1),
        (262, 20, 'Guásimos', current_timestamp, current_timestamp, 1, 1),
        (263, 20, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (264, 20, 'Jáuregui', current_timestamp, current_timestamp, 1, 1),
        (265, 20, 'José María Vargas', current_timestamp, current_timestamp, 1, 1),
        (266, 20, 'Junín', current_timestamp, current_timestamp, 1, 1),
        (267, 20, 'Libertad', current_timestamp, current_timestamp, 1, 1),
        (268, 20, 'Libertador', current_timestamp, current_timestamp, 1, 1),
        (269, 20, 'Lobatera', current_timestamp, current_timestamp, 1, 1),
        (270, 20, 'Michelena', current_timestamp, current_timestamp, 1, 1),
        (271, 20, 'Panamericano', current_timestamp, current_timestamp, 1, 1),
        (272, 20, 'Pedro María Ureña', current_timestamp, current_timestamp, 1, 1),
        (273, 20, 'Rafael Urdaneta', current_timestamp, current_timestamp, 1, 1),
        (274, 20, 'Samuel Darío Maldonado', current_timestamp, current_timestamp, 1, 1),
        (275, 20, 'San Cristóbal', current_timestamp, current_timestamp, 1, 1),
        (276, 20, 'Seboruco', current_timestamp, current_timestamp, 1, 1),
        (277, 20, 'Simón Rodríguez', current_timestamp, current_timestamp, 1, 1),
        (278, 20, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (279, 20, 'Torbes', current_timestamp, current_timestamp, 1, 1),
        (280, 20, 'Uribante', current_timestamp, current_timestamp, 1, 1),
        (281, 20, 'San Judas Tadeo', current_timestamp, current_timestamp, 1, 1),
        (282, 21, 'Andrés Bello', current_timestamp, current_timestamp, 1, 1),
        (283, 21, 'Boconó', current_timestamp, current_timestamp, 1, 1),
        (284, 21, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (285, 21, 'Candelaria', current_timestamp, current_timestamp, 1, 1),
        (286, 21, 'Carache', current_timestamp, current_timestamp, 1, 1),
        (287, 21, 'Escuque', current_timestamp, current_timestamp, 1, 1),
        (288, 21, 'José Felipe Márquez Cañizalez', current_timestamp, current_timestamp, 1, 1),
        (289, 21, 'Juan Vicente Campos Elías', current_timestamp, current_timestamp, 1, 1),
        (290, 21, 'La Ceiba', current_timestamp, current_timestamp, 1, 1),
        (291, 21, 'Miranda', current_timestamp, current_timestamp, 1, 1),
        (292, 21, 'Monte Carmelo', current_timestamp, current_timestamp, 1, 1),
        (293, 21, 'Motatán', current_timestamp, current_timestamp, 1, 1),
        (294, 21, 'Pampán', current_timestamp, current_timestamp, 1, 1),
        (295, 21, 'Pampanito', current_timestamp, current_timestamp, 1, 1),
        (296, 21, 'Rafael Rangel', current_timestamp, current_timestamp, 1, 1),
        (297, 21, 'San Rafael de Carvajal', current_timestamp, current_timestamp, 1, 1),
        (298, 21, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (299, 21, 'Trujillo', current_timestamp, current_timestamp, 1, 1),
        (300, 21, 'Urdaneta', current_timestamp, current_timestamp, 1, 1),
        (301, 21, 'Valera', current_timestamp, current_timestamp, 1, 1),
        (302, 22, 'Veroes', current_timestamp, current_timestamp, 1, 1),
        (303, 22, 'Arístides Bastidas', current_timestamp, current_timestamp, 1, 1),
        (304, 22, 'Bolívar', current_timestamp, current_timestamp, 1, 1),
        (305, 22, 'Bruzal', current_timestamp, current_timestamp, 1, 1),
        (306, 22, 'Cocorote', current_timestamp, current_timestamp, 1, 1),
        (307, 22, 'Independencia', current_timestamp, current_timestamp, 1, 1),
        (308, 22, 'José Antonio Páez', current_timestamp, current_timestamp, 1, 1),
        (309, 22, 'La Trinidad', current_timestamp, current_timestamp, 1, 1),
        (310, 22, 'Manuel Monge', current_timestamp, current_timestamp, 1, 1),
        (311, 22, 'Nirgua', current_timestamp, current_timestamp, 1, 1),
        (312, 22, 'Peña', current_timestamp, current_timestamp, 1, 1),
        (313, 22, 'San Felipe', current_timestamp, current_timestamp, 1, 1),
        (314, 22, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (315, 22, 'Urachiche', current_timestamp, current_timestamp, 1, 1),
        (316, 24, 'Almirante Padilla', current_timestamp, current_timestamp, 1, 1),
        (317, 24, 'Baralt', current_timestamp, current_timestamp, 1, 1),
        (318, 24, 'Cabimas', current_timestamp, current_timestamp, 1, 1),
        (319, 24, 'Catatumbo', current_timestamp, current_timestamp, 1, 1),
        (320, 24, 'Colón', current_timestamp, current_timestamp, 1, 1),
        (321, 24, 'Francisco Javier Pulgar', current_timestamp, current_timestamp, 1, 1),
        (322, 24, 'Jesús Enrique Losada', current_timestamp, current_timestamp, 1, 1),
        (323, 24, 'La Cañada de Urdaneta', current_timestamp, current_timestamp, 1, 1),
        (324, 24, 'Lagunillas', current_timestamp, current_timestamp, 1, 1),
        (325, 24, 'Machiques de Perijá', current_timestamp, current_timestamp, 1, 1),
        (326, 24, 'Mara', current_timestamp, current_timestamp, 1, 1),
        (327, 24, 'Maracaibo', current_timestamp, current_timestamp, 1, 1),
        (328, 24, 'Miranda', current_timestamp, current_timestamp, 1, 1),
        (329, 24, 'Páez', current_timestamp, current_timestamp, 1, 1),
        (330, 24, 'Rosario de Perijá', current_timestamp, current_timestamp, 1, 1),
        (331, 24, 'San Francisco', current_timestamp, current_timestamp, 1, 1),
        (332, 24, 'Santa Rita', current_timestamp, current_timestamp, 1, 1),
        (333, 24, 'Simón Bolívar', current_timestamp, current_timestamp, 1, 1),
        (334, 24, 'Sucre', current_timestamp, current_timestamp, 1, 1),
        (335, 24, 'Valmore Rodríguez', current_timestamp, current_timestamp, 1, 1),
        (336, 24, 'Jesús María Semprún', current_timestamp, current_timestamp, 1, 1);";

    /**
     * Run the database seeds.
     *
     * @return void
     */
    public function run()
    {
        $this->command->comment('Empezando ' . __CLASS__);

        DB::statement($this->towns);
    }
}
